#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def resolve_project_path(path_text: str) -> Path:
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def score_candidate(candidate: dict, weights: dict) -> tuple[float, dict]:
    breakdown = {}
    total = 0.0
    for field, weight in weights.items():
        value = candidate[field]
        weighted = value * weight
        breakdown[field] = {
            "value": value,
            "weight": weight,
            "weighted_score": round(weighted, 3),
        }
        total += weighted
    return round(total, 3), breakdown


def rank_candidates(payload: dict) -> list[dict]:
    weights = payload["scoring_weights"]
    ranked = []
    for candidate in payload["candidates"]:
        score, breakdown = score_candidate(candidate, weights)
        ranked.append({
            **candidate,
            "weighted_score": score,
            "score_breakdown": breakdown,
        })
    return sorted(ranked, key=lambda item: (-item["weighted_score"], item["provider_id"]))


def first_matching(candidates: list[dict], predicate) -> dict:
    for candidate in candidates:
        if predicate(candidate):
            return candidate
    raise SystemExit("No candidate matched recommendation criteria.")


def build_recommendations(ranked: list[dict]) -> dict:
    regression_baseline = first_matching(
        ranked,
        lambda candidate: candidate["provider_id"] == "manual-transcript-baseline",
    )
    next_prototype = first_matching(
        ranked,
        lambda candidate: (
            candidate["requires_api_key"] is False
            and candidate["provider_id"] != "manual-transcript-baseline"
        ),
    )
    production_followup = first_matching(
        ranked,
        lambda candidate: candidate["provider_id"] == "cloud-streaming-asr-class",
    )
    return {
        "regression_baseline": summarize_candidate(regression_baseline),
        "next_prototype": summarize_candidate(next_prototype),
        "production_followup": summarize_candidate(production_followup),
    }


def summarize_candidate(candidate: dict) -> dict:
    return {
        "provider_id": candidate["provider_id"],
        "provider_family": candidate["provider_family"],
        "role": candidate["role"],
        "requires_api_key": candidate["requires_api_key"],
        "weighted_score": candidate["weighted_score"],
        "decision_notes": candidate["decision_notes"],
    }


def build_result(payload: dict) -> dict:
    ranked = rank_candidates(payload)
    return {
        "voice_milestone": payload["voice_milestone"],
        "comparison_scope": payload["comparison_scope"],
        "summary": {
            "candidate_count": len(ranked),
            "api_calls_made": False,
            "audio_uploaded": False,
            "score_scale": payload["score_scale"],
        },
        "scoring_weights": payload["scoring_weights"],
        "recommendations": build_recommendations(ranked),
        "ranked_candidates": ranked,
    }


def render_report(result: dict) -> str:
    recommendations = result["recommendations"]
    lines = [
        "# VOICE-003 ASR Provider Comparison Report",
        "",
        "This report was generated by `scripts/compare_asr_providers.py`.",
        "",
        "No API calls were made and no audio was uploaded.",
        "",
        "The comparison evaluates provider families, not final vendor commitments.",
        "",
        "## Adapter Boundary",
        "",
        "Every future ASR provider should produce the same adapter boundary:",
        "",
        "```text",
        "audio input -> transcript text -> confidence/quality metadata -> provider metadata -> consent/privacy metadata",
        "```",
        "",
        "## Recommendations",
        "",
        f"- Regression baseline: `{recommendations['regression_baseline']['provider_id']}`",
        f"- Next no-key prototype: `{recommendations['next_prototype']['provider_id']}`",
        f"- Production follow-up class: `{recommendations['production_followup']['provider_id']}`",
        "",
        "Cloud ASR classes remain gated behind explicit key management, privacy review, and data-retention decisions.",
        "",
        "## Ranked Candidates",
        "",
    ]
    for index, candidate in enumerate(result["ranked_candidates"], start=1):
        notes = " ".join(candidate["decision_notes"])
        lines.extend(
            [
                f"### {index}. {candidate['provider_id']}",
                "",
                f"- Family: {candidate['provider_family']}",
                f"- Role: `{candidate['role']}`",
                f"- Requires API key: `{str(candidate['requires_api_key']).lower()}`",
                f"- Weighted score: `{candidate['weighted_score']}`",
                f"- Adapter boundary: {candidate['adapter_boundary']}",
                f"- Notes: {notes}",
                "",
            ]
        )
    return "\n".join(lines)


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare VOICE-003 ASR provider families.")
    parser.add_argument("--providers", required=True, help="Path to ASR provider-family candidate JSON.")
    parser.add_argument("--out", required=True, help="Path to write JSON comparison results.")
    parser.add_argument("--report-out", required=True, help="Path to write Markdown comparison report.")
    args = parser.parse_args()

    payload = load_json(resolve_project_path(args.providers))
    result = build_result(payload)

    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    write_json(out_path, result)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(render_report(result), encoding="utf-8")

    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
