#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from generate_guarded_response import build_guarded_response_packet
from realtime_turn_cli import find_campaign
from run_realtime_turn_simulation import load_realtime_cases
from runtime_voice_delivery import attach_runtime_voice_delivery


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES_PATH = ROOT / "research" / "experiments" / "cases" / "prod-005-realtime-latency-call-control.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "RESP-002" / "RESP-002-runtime-voice-delivery-result.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "RESP-002" / "RESP-002-runtime-voice-delivery-report.md"


def resolve_project_path(path_text: str | None) -> Path | None:
    if path_text is None:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def render_report(packet: dict) -> str:
    delivery = packet["voice_delivery"]
    provider = delivery["provider_rendering"]
    spoken = delivery["spoken_text_normalization"]
    interaction = delivery["speech_interaction"]
    imperfections = delivery["speech_imperfections"]
    prosody = delivery["prosody"]
    pacing = delivery["voice_pacing_calibration"]
    connected = delivery["voice_connected_speech"]
    listening = delivery["voice_listening_calibration"]
    emotion_smoothing = delivery["voice_emotion_smoothing"]
    semantic_emphasis = delivery["voice_semantic_emphasis"]
    low_pressure_focus = delivery["voice_low_pressure_focus"]
    baseline_delivery_polish = delivery["voice_baseline_delivery_polish"]
    private_pattern_profile = delivery["voice_private_pattern_profile"]
    validation = delivery["validation"]
    decision = packet["decision_snapshot"]
    lines = [
        "# RESP-002 Runtime Voice Delivery Report",
        "",
        "This report was generated by `scripts/generate_runtime_voice_delivery.py`.",
        "",
        "RESP-002 runs after RESP-001. It prepares guarded text for voice delivery without changing the guarded final response and without calling a TTS provider.",
        "",
        "## Result",
        "",
        f"- Campaign: `{packet['campaign']['campaign_id']}`",
        f"- Provider preview: `{delivery['provider_key']}`",
        f"- Sales difficulty: `{decision['sales_difficulty']}`",
        f"- Strategy: `{decision['selected_strategy']}`",
        f"- Call control: `{decision['call_control']}`",
        f"- Final response unchanged: `{delivery['final_response_unchanged']}`",
        f"- Spoken-text normalizations: `{spoken['normalization_count']}`",
        f"- Interaction markers: `{interaction['marker_count']}`",
        f"- Controlled imperfections: `{imperfections['imperfection_count']}`",
        f"- Pacing calibrated: `{delivery['provider_rendering'].get('pacing_calibrated', False)}`",
        f"- Avg voice speed ratio: `{pacing['average_speed_ratio']}`",
        f"- Connected-speech flow joins: `{connected['flow_join_count']}`",
        f"- Listening calibration adjustments: `{listening['listening_adjustment_count']}`",
        f"- Emphasis targets blocked: `{listening['emphasis_guard']['blocked_emphasis_count']}`",
        f"- Emotion transitions smoothed: `{emotion_smoothing['smoothed_transition_count']}`",
        f"- Over-emotional cues blocked: `{emotion_smoothing['blocked_overemotional_cue_count']}`",
        f"- Semantic emphasis rewrites: `{semantic_emphasis['rewrite_count']}`",
        f"- Low-pressure focus rewrites: `{low_pressure_focus['rewrite_count']}`",
        f"- Baseline delivery polish adjustments: `{baseline_delivery_polish['adjustment_count']}`",
        f"- Private pattern profile applied: `{private_pattern_profile['applied']}`",
        f"- Provider calls made: `{delivery['provider_calls_made']}`",
        f"- Requires API key: `{delivery['requires_api_key']}`",
        f"- Customer audio uploaded: `{delivery['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{delivery['voice_cloning_used']}`",
        f"- Validation passed: `{validation['passed']}`",
        "",
        "## Delivery Segments",
        "",
    ]
    for segment in delivery["segments"]:
        lines.extend(
            [
                f"- `{segment['segment_id']}`",
                f"  type: `{segment['segment_type']}`",
                f"  eligible for prosody: `{segment['allow_prosody']}`",
            ]
        )
    lines.extend(
        [
            "",
            "## Spoken Text Normalization",
            "",
            f"- Validation passed: `{spoken['validation']['passed']}`",
            f"- Eligible segments: `{spoken['eligible_segment_count']}`",
            f"- Protected segments: `{spoken['protected_segment_count']}`",
            f"- Normalization count: `{spoken['normalization_count']}`",
            f"- Spoken TTS text: {spoken['tts_text']}",
        ]
    )
    for operation in spoken["normalizations"]:
        lines.append(
            f"- `{operation['rule_id']}` on `{operation['segment_id']}`: `{operation['before']}` -> `{operation['after']}`"
        )
    lines.extend(
        [
            "",
            "## Interaction Prosody",
            "",
            f"- Validation passed: `{interaction['validation']['passed']}`",
            f"- Marker count: `{interaction['marker_count']}`",
            f"- Unsafe claim context: `{interaction['unsafe_claim_context']}`",
            f"- Interaction TTS text: {interaction['tts_text']}",
        ]
    )
    for marker in interaction["interaction_markers"]:
        lines.append(
            f"- `{marker['marker_type']}` on `{marker['segment_id']}`: visible `{marker['visible']}`, placement `{marker['placement']}`, phrase `{marker['marker_text']}`, rate `{marker['rate_multiplier']}`, pitch `{marker['pitch_intent']}`"
        )
    lines.extend(
        [
            "",
            "## Controlled Imperfections",
            "",
            f"- Validation passed: `{imperfections['validation']['passed']}`",
            f"- Imperfection count: `{imperfections['imperfection_count']}`",
            f"- Unsafe claim context: `{imperfections['unsafe_claim_context']}`",
            f"- Imperfection TTS text: {imperfections['tts_text']}",
        ]
    )
    for imperfection in imperfections["imperfections"]:
        lines.append(
            f"- `{imperfection['imperfection_type']}` on `{imperfection['segment_id']}`: visible `{imperfection['visible']}`, placement `{imperfection['placement']}`, phrase `{imperfection['marker_text']}`, pause `{imperfection['pause_ms']}ms`"
        )
    lines.extend(
        [
            "",
            "## Prosody",
            "",
            f"- Cue count: `{prosody['cue_count']}`",
            f"- Cue counts: `{json.dumps(prosody['cue_counts'], ensure_ascii=False)}`",
            f"- Protected segment cue count: `{prosody['protected_segment_cue_count']}`",
            "",
            "## Pacing Calibration",
            "",
            f"- Calibration ID: `{pacing['voice_pacing_calibration_id']}`",
            f"- Language: `{pacing['language']}`",
            f"- Tuned segments: `{pacing['tuned_segment_count']}`",
            f"- German word-gap reduction: `{pacing['german_word_gap_reduction_applied']}`",
            f"- Avg break before: `{pacing['average_break_duration_before_ms']}` ms",
            f"- Avg break after: `{pacing['average_break_duration_after_ms']}` ms",
            f"- Validation passed: `{pacing['validation']['passed']}`",
            "",
            "## Connected Speech",
            "",
            f"- Connected speech ID: `{connected['voice_connected_speech_id']}`",
            f"- Language: `{connected['language']}`",
            f"- Flow joins: `{connected['flow_join_count']}`",
            f"- Tuned segments: `{connected['tuned_segment_count']}`",
            f"- Validation passed: `{connected['validation']['passed']}`",
            "",
            "## Listening Calibration",
            "",
            f"- Calibration ID: `{listening['voice_listening_calibration_id']}`",
            f"- Language: `{listening['language']}`",
            f"- German connected speech relaxed: `{listening['german_connected_speech_relaxed']}`",
            f"- Listening adjustments: `{listening['listening_adjustment_count']}`",
            f"- Blocked emphasis count: `{listening['emphasis_guard']['blocked_emphasis_count']}`",
            f"- Validation passed: `{listening['validation']['passed']}`",
            "",
            "## Emotion Transition Smoothing",
            "",
            f"- Smoothing ID: `{emotion_smoothing['voice_emotion_smoothing_id']}`",
            f"- Language: `{emotion_smoothing['language']}`",
            f"- Eligible for smoothing: `{emotion_smoothing['eligible_for_smoothing']}`",
            f"- Transition smoothing applied: `{emotion_smoothing['transition_smoothing_applied']}`",
            f"- Detected transitions: `{emotion_smoothing['detected_transition_count']}`",
            f"- Smoothed transitions: `{emotion_smoothing['smoothed_transition_count']}`",
            f"- Blocked over-emotional cues: `{emotion_smoothing['blocked_overemotional_cue_count']}`",
            f"- Validation passed: `{emotion_smoothing['validation']['passed']}`",
            "",
            "## Semantic Emphasis",
            "",
            f"- Semantic emphasis ID: `{semantic_emphasis['voice_semantic_emphasis_id']}`",
            f"- Language: `{semantic_emphasis['language']}`",
            f"- Language allowed: `{semantic_emphasis['language_allowed']}`",
            f"- Eligible segments: `{semantic_emphasis['eligible_segment_count']}`",
            f"- Protected segments: `{semantic_emphasis['protected_segment_count']}`",
            f"- Rewrites: `{semantic_emphasis['rewrite_count']}`",
            f"- Validation passed: `{semantic_emphasis['validation']['passed']}`",
            "",
            "## Low-Pressure Focus",
            "",
            f"- Low-pressure focus ID: `{low_pressure_focus['voice_low_pressure_focus_id']}`",
            f"- Language: `{low_pressure_focus['language']}`",
            f"- Language allowed: `{low_pressure_focus['language_allowed']}`",
            f"- Eligible segments: `{low_pressure_focus['eligible_segment_count']}`",
            f"- Protected segments: `{low_pressure_focus['protected_segment_count']}`",
            f"- Rewrites: `{low_pressure_focus['rewrite_count']}`",
            f"- Validation passed: `{low_pressure_focus['validation']['passed']}`",
            "",
            "## Baseline Delivery Polish",
            "",
            f"- Polish ID: `{baseline_delivery_polish['voice_baseline_delivery_polish_id']}`",
            f"- Enabled: `{baseline_delivery_polish['enabled']}`",
            f"- Applied: `{baseline_delivery_polish['applied']}`",
            f"- Adjustments: `{baseline_delivery_polish['adjustment_count']}`",
            f"- Validation passed: `{baseline_delivery_polish['validation']['passed']}`",
            "",
            "## Private Pattern Profile",
            "",
            f"- Profile ID: `{private_pattern_profile['voice_private_pattern_profile_id']}`",
            f"- Enabled: `{private_pattern_profile['enabled']}`",
            f"- Applied: `{private_pattern_profile['applied']}`",
            f"- Blocked reason: `{private_pattern_profile['blocked_reason']}`",
            f"- Rhythm density action: `{private_pattern_profile['rhythm_density_action']}`",
            f"- Presence action: `{private_pattern_profile['presence_action']}`",
            f"- Setting adjustments: `{private_pattern_profile['setting_adjustments']}`",
            f"- Validation passed: `{private_pattern_profile['validation']['passed']}`",
            "",
            "## Provider Rendering",
            "",
            f"- Provider rendering mode: `{provider['provider_rendering_mode']}`",
            f"- Provider tag count: `{provider['provider_tag_count']}`",
            f"- Protected segment provider tag count: `{provider['protected_segment_provider_tag_count']}`",
            f"- API call made: `{provider['api_call_made']}`",
            "",
            "## Text",
            "",
            f"- Final response: {packet['final_response']}",
            f"- Clean TTS text: {prosody['tts_text']}",
            f"- Provider-rendered text: {provider['rendered_text']}",
            "",
            "## Boundary",
            "",
            "RESP-002 may shape delivery metadata and provider-specific TTS input. It must not change the guarded final response, state, strategy, next action, call control, or campaign guardrails.",
        ]
    )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate RESP-002 runtime voice delivery from guarded response output.")
    parser.add_argument("--campaign", required=True, help="Campaign ID to use.")
    parser.add_argument("--stage", required=True, help="Current call stage.")
    parser.add_argument("--transcript", default="", help="Customer transcript for this turn.")
    parser.add_argument(
        "--input-type",
        default="speech-final",
        choices=["speech-final", "voicemail-detected", "silence-timeout"],
        help="Runtime input type.",
    )
    parser.add_argument("--silence-count", type=int, default=0, help="Silence retry count for silence-timeout input.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES_PATH), help="Campaign wrapper case file to load.")
    parser.add_argument("--candidate-response", help="Optional candidate response override for guardrail testing.")
    parser.add_argument("--provider", choices=["elevenlabs", "cartesia"], default="elevenlabs", help="Provider preview to render.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Path to write JSON output.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Path to write a Markdown report.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    if cases_path is None:
        raise SystemExit("--cases is required.")
    campaigns, _cases = load_realtime_cases(cases_path)
    campaign = find_campaign(campaigns, args.campaign)
    guarded_packet = build_guarded_response_packet(
        campaign=campaign,
        stage=args.stage,
        input_type=args.input_type,
        transcript=args.transcript,
        silence_count=args.silence_count,
        candidate_response_override=args.candidate_response,
    )
    packet = attach_runtime_voice_delivery(guarded_packet, campaign, provider_key=args.provider)

    out_path = resolve_project_path(args.out)
    if out_path is not None:
        write_json(out_path, packet)

    report_path = resolve_project_path(args.report_out)
    if report_path is not None:
        write_text(report_path, render_report(packet))

    print(json.dumps(packet, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
