#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from generate_guarded_response import build_guarded_response_packet
from realtime_turn_cli import find_campaign
from run_realtime_turn_simulation import load_realtime_cases
from runtime_voice_delivery import attach_runtime_voice_delivery


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES_PATH = ROOT / "research" / "experiments" / "cases" / "prod-005-realtime-latency-call-control.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "RESP-002-runtime-voice-delivery-result.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "RESP-002-runtime-voice-delivery-report.md"


def resolve_project_path(path_text: str | None) -> Path | None:
    if path_text is None:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def render_report(packet: dict) -> str:
    delivery = packet["voice_delivery"]
    provider = delivery["provider_rendering"]
    prosody = delivery["prosody"]
    validation = delivery["validation"]
    decision = packet["decision_snapshot"]
    lines = [
        "# RESP-002 Runtime Voice Delivery Report",
        "",
        "This report was generated by `scripts/generate_runtime_voice_delivery.py`.",
        "",
        "RESP-002 runs after RESP-001. It prepares guarded text for voice delivery without changing the guarded final response and without calling a TTS provider.",
        "",
        "## Result",
        "",
        f"- Campaign: `{packet['campaign']['campaign_id']}`",
        f"- Provider preview: `{delivery['provider_key']}`",
        f"- Sales difficulty: `{decision['sales_difficulty']}`",
        f"- Strategy: `{decision['selected_strategy']}`",
        f"- Call control: `{decision['call_control']}`",
        f"- Final response unchanged: `{delivery['final_response_unchanged']}`",
        f"- Provider calls made: `{delivery['provider_calls_made']}`",
        f"- Requires API key: `{delivery['requires_api_key']}`",
        f"- Customer audio uploaded: `{delivery['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{delivery['voice_cloning_used']}`",
        f"- Validation passed: `{validation['passed']}`",
        "",
        "## Delivery Segments",
        "",
    ]
    for segment in delivery["segments"]:
        lines.extend(
            [
                f"- `{segment['segment_id']}`",
                f"  type: `{segment['segment_type']}`",
                f"  eligible for prosody: `{segment['allow_prosody']}`",
            ]
        )
    lines.extend(
        [
            "",
            "## Prosody",
            "",
            f"- Cue count: `{prosody['cue_count']}`",
            f"- Cue counts: `{json.dumps(prosody['cue_counts'], ensure_ascii=False)}`",
            f"- Protected segment cue count: `{prosody['protected_segment_cue_count']}`",
            "",
            "## Provider Rendering",
            "",
            f"- Provider rendering mode: `{provider['provider_rendering_mode']}`",
            f"- Provider tag count: `{provider['provider_tag_count']}`",
            f"- Protected segment provider tag count: `{provider['protected_segment_provider_tag_count']}`",
            f"- API call made: `{provider['api_call_made']}`",
            "",
            "## Text",
            "",
            f"- Final response: {packet['final_response']}",
            f"- Clean TTS text: {prosody['tts_text']}",
            f"- Provider-rendered text: {provider['rendered_text']}",
            "",
            "## Boundary",
            "",
            "RESP-002 may shape delivery metadata and provider-specific TTS input. It must not change the guarded final response, state, strategy, next action, call control, or campaign guardrails.",
        ]
    )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate RESP-002 runtime voice delivery from guarded response output.")
    parser.add_argument("--campaign", required=True, help="Campaign ID to use.")
    parser.add_argument("--stage", required=True, help="Current call stage.")
    parser.add_argument("--transcript", default="", help="Customer transcript for this turn.")
    parser.add_argument(
        "--input-type",
        default="speech-final",
        choices=["speech-final", "voicemail-detected", "silence-timeout"],
        help="Runtime input type.",
    )
    parser.add_argument("--silence-count", type=int, default=0, help="Silence retry count for silence-timeout input.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES_PATH), help="Campaign wrapper case file to load.")
    parser.add_argument("--candidate-response", help="Optional candidate response override for guardrail testing.")
    parser.add_argument("--provider", choices=["elevenlabs", "cartesia"], default="elevenlabs", help="Provider preview to render.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Path to write JSON output.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Path to write a Markdown report.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    if cases_path is None:
        raise SystemExit("--cases is required.")
    campaigns, _cases = load_realtime_cases(cases_path)
    campaign = find_campaign(campaigns, args.campaign)
    guarded_packet = build_guarded_response_packet(
        campaign=campaign,
        stage=args.stage,
        input_type=args.input_type,
        transcript=args.transcript,
        silence_count=args.silence_count,
        candidate_response_override=args.candidate_response,
    )
    packet = attach_runtime_voice_delivery(guarded_packet, campaign, provider_key=args.provider)

    out_path = resolve_project_path(args.out)
    if out_path is not None:
        write_json(out_path, packet)

    report_path = resolve_project_path(args.report_out)
    if report_path is not None:
        write_text(report_path, render_report(packet))

    print(json.dumps(packet, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
