#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from generate_guarded_response import build_guarded_response_packet
from realtime_turn_cli import find_campaign
from run_realtime_turn_simulation import load_realtime_cases
from runtime_tts_delivery import attach_runtime_tts_delivery
from runtime_voice_delivery import attach_runtime_voice_delivery


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES_PATH = ROOT / "research" / "experiments" / "cases" / "prod-005-realtime-latency-call-control.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "RESP-003-runtime-live-tts-result.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "RESP-003-runtime-live-tts-report.md"
DEFAULT_AUDIO_DIR = ROOT / "research" / "experiments" / "generated"


def resolve_project_path(path_text: str | None) -> Path | None:
    if path_text is None:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def render_report(packet: dict) -> str:
    tts = packet["tts_delivery"]
    asset_log = tts["asset_log"]
    validation = tts["validation"]
    decision = packet["decision_snapshot"]
    lines = [
        "# RESP-003 Runtime Live TTS Report",
        "",
        "This report was generated by `scripts/generate_runtime_tts_delivery.py`.",
        "",
        "RESP-003 runs after RESP-002. It can turn provider-ready guarded text into audio, but the default mode is dry-run and makes no provider calls.",
        "",
        "## Result",
        "",
        f"- Campaign: `{packet['campaign']['campaign_id']}`",
        f"- Provider: `{tts['provider_key']}`",
        f"- Sales difficulty: `{decision['sales_difficulty']}`",
        f"- Strategy: `{decision['selected_strategy']}`",
        f"- Call control: `{decision['call_control']}`",
        f"- Live call requested: `{tts['live_call_requested']}`",
        f"- Provider calls made: `{tts['provider_calls_made']}`",
        f"- Generated text sent to provider: `{tts['generated_text_sent_to_provider']}`",
        f"- Audio file created: `{tts['audio_file_created']}`",
        f"- Audio path: `{tts['audio_output_path'] or 'not created'}`",
        f"- Fallback used: `{tts['fallback_used']}`",
        f"- Fallback reason: `{tts['fallback_reason'] or 'not needed'}`",
        f"- Customer audio uploaded: `{tts['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{tts['voice_cloning_used']}`",
        f"- API key env var: `{tts['api_key_env_var']}`",
        f"- Selected voice env var: `{tts['selected_voice_id_env_var']}`",
        f"- API key value logged: `{tts['api_key_value_logged']}`",
        f"- Voice ID value logged: `{tts['voice_id_value_logged']}`",
        f"- Timeout seconds: `{tts['timeout_seconds']}`",
        f"- Validation passed: `{validation['passed']}`",
        "",
        "## TTS Input",
        "",
        f"- Input source: `{tts['tts_input_source']}`",
        f"- Provider rendering used: `{tts['provider_rendering_used']}`",
        f"- TTS input chars: `{len(tts['tts_input_text'])}`",
        "",
        "## Asset Log Summary",
        "",
        f"- Asset status: `{asset_log['status']}`",
        f"- Output path: `{asset_log['output_path'] or 'not created'}`",
        f"- API key location: `{asset_log['run_boundary']['api_key_location']}`",
        f"- Network used: `{asset_log['run_boundary']['network_used']}`",
        f"- Upload used: `{asset_log['run_boundary']['upload_used']}`",
        f"- Human listening review: `{asset_log['review']['human_listening_review']}`",
        "",
        "## Text",
        "",
        f"- Final response: {packet['final_response']}",
        f"- TTS input: {tts['tts_input_text']}",
        "",
        "## Boundary",
        "",
        "RESP-003 may create synthetic TTS audio from approved runtime text. It must not change the guarded response, upload customer audio, clone voices, or store provider secrets.",
    ]
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate RESP-003 runtime live-capable TTS delivery from guarded response output.")
    parser.add_argument("--campaign", required=True, help="Campaign ID to use.")
    parser.add_argument("--stage", required=True, help="Current call stage.")
    parser.add_argument("--transcript", default="", help="Customer transcript for this turn.")
    parser.add_argument(
        "--input-type",
        default="speech-final",
        choices=["speech-final", "voicemail-detected", "silence-timeout"],
        help="Runtime input type.",
    )
    parser.add_argument("--silence-count", type=int, default=0, help="Silence retry count for silence-timeout input.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES_PATH), help="Campaign wrapper case file to load.")
    parser.add_argument("--candidate-response", help="Optional candidate response override for guardrail testing.")
    parser.add_argument("--provider", choices=["elevenlabs", "cartesia"], default="elevenlabs", help="TTS provider to prepare or call.")
    parser.add_argument("--audio-dir", default=str(DEFAULT_AUDIO_DIR), help="Directory for generated audio files.")
    parser.add_argument("--timeout-seconds", type=float, default=8.0, help="Provider request timeout. Must be <= 10.")
    parser.add_argument("--live", action="store_true", help="Allow live provider API calls when env gates are satisfied.")
    parser.add_argument("--force-key-missing", action="store_true", help="Ignore provider env vars to validate missing-key fallback.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Path to write JSON output.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Path to write a Markdown report.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.timeout_seconds <= 0 or args.timeout_seconds > 10:
        raise SystemExit("--timeout-seconds must be greater than 0 and no more than 10.")

    cases_path = resolve_project_path(args.cases)
    audio_dir = resolve_project_path(args.audio_dir)
    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    if cases_path is None or audio_dir is None or out_path is None or report_path is None:
        raise SystemExit("Cases, audio, output, and report paths are required.")

    campaigns, _cases = load_realtime_cases(cases_path)
    campaign = find_campaign(campaigns, args.campaign)
    guarded_packet = build_guarded_response_packet(
        campaign=campaign,
        stage=args.stage,
        input_type=args.input_type,
        transcript=args.transcript,
        silence_count=args.silence_count,
        candidate_response_override=args.candidate_response,
    )
    voice_packet = attach_runtime_voice_delivery(guarded_packet, campaign, provider_key=args.provider)
    packet = attach_runtime_tts_delivery(
        voice_packet,
        provider_key=args.provider,
        live=args.live,
        force_key_missing=args.force_key_missing,
        audio_dir=audio_dir,
        timeout_seconds=args.timeout_seconds,
    )

    write_json(out_path, packet)
    write_text(report_path, render_report(packet))
    print(json.dumps(packet, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
