#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def format_value(value):
    if value is None:
        return "`null`"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    return f"`{value}`"


def build_case_section(case: dict) -> str:
    lines = [
        f"## {case['case_id']}: {case['case_title']}",
        "",
        f"- Scenario goal: {case['scenario_goal']}",
        f"- Lead role: `{case['lead_profile']['role']}`",
        f"- Company context: {case['lead_profile']['company_context']}",
        f"- Starting attitude: `{case['lead_profile']['starting_attitude']}`",
        "",
        "### Turn Script",
        "",
    ]

    for index, turn in enumerate(case["turns"], start=1):
        lines.extend(
            [
                f"#### Turn {index}: `{turn['stage']}`",
                "",
                "Agent question:",
                "",
                "```text",
                turn["agent_question"],
                "```",
                "",
                "Lead answer:",
                "",
                "```text",
                turn["lead_answer"],
                "```",
                "",
                f"- Emotion label: `{turn['emotion_label']}`",
                f"- Expected state after turn: `{turn['expected_state_after_turn']}`",
                f"- Strategy label: `{turn['strategy_label']}`",
                f"- Expected agent action: {turn['expected_agent_action']}",
                "",
            ]
        )

    outcome = case["expected_outcome"]
    lines.extend(
        [
            "### Expected CallOutcome",
            "",
            f"- Call status: `{outcome['call_status']}`",
            f"- Interest state: `{outcome['interest_state']}`",
            f"- Selected strategy: `{outcome['selected_strategy']}`",
            f"- Appointment scheduled: {format_value(outcome['appointment_scheduled'])}",
            f"- Appointment time: {format_value(outcome['appointment_time'])}",
            f"- Escalation reason: {format_value(outcome['escalation_reason'])}",
            f"- Next action: {outcome['next_action']}",
            "",
            "### Guardrail Notes",
            "",
        ]
    )
    lines.extend(f"- {note}" for note in case.get("guardrail_notes", []))
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Render a product MVP turn-based simulation packet.")
    parser.add_argument("--cases", required=True, help="Path to the JSON simulation case file.")
    parser.add_argument("--out", required=True, help="Path to the markdown output file.")
    args = parser.parse_args()

    cases_path = Path(args.cases)
    out_path = Path(args.out)
    cases = load_json(cases_path)

    header = [
        f"# Product MVP Simulation Packet: {cases_path.stem}",
        "",
        "This file was generated by `scripts/render_product_simulation.py`.",
        "",
        f"- Source case file: `{cases_path.as_posix()}`",
        f"- Cases: {len(cases)}",
        "- Source label: `product-synthetic`",
        "",
        "Purpose: exercise the autonomous qualification and appointment-setting workflow before real telephony integration.",
        "",
        "Use this packet to test whether the agent asks the right qualification question, estimates interest state, selects an appropriate strategy, and produces the correct scheduling or escalation outcome.",
        "",
    ]

    sections = [build_case_section(case) for case in cases]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(header + sections), encoding="utf-8")


if __name__ == "__main__":
    main()
