#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from voice_feature_runtime_mapping import build_runtime_mapping_plan


ROOT = Path(__file__).resolve().parents[1]
PRIVATE_DATA_ROOT = ROOT / "data" / "private"
CASE_PATH = ROOT / "research" / "experiments" / "cases" / "voice-031-feature-runtime-mapping.json"
DEFAULT_PUBLIC_OUT_DIR = ROOT / "research" / "experiments" / "generated" / "VOICE-031-feature-runtime-mapping"


def is_under(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def project_relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def resolve_project_path(value: str | None, default: Path | None = None) -> Path:
    if value:
        path = Path(value)
        return path if path.is_absolute() else ROOT / path
    if default is None:
        raise SystemExit("Missing required path.")
    return default


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_case(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise SystemExit(f"VOICE-031 case file is missing: {project_relative(path)}")
    return load_json(path)


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def render_report(payload: dict[str, Any]) -> str:
    lines = [
        "# VOICE-031 Feature-To-Runtime Mapping Gate",
        "",
        "This report was generated by `scripts/run_voice_031_feature_runtime_mapping.py`.",
        "",
        "VOICE-031 is proposal only. It does not apply runtime settings, call providers, transcribe audio, read raw audio, or clone voices.",
        "",
        "## Result",
        "",
        f"- Mapping status: `{payload['mapping_status']}`",
        f"- Source label: `{payload['source_label']}`",
        f"- Runtime profile applied: `{payload['runtime_profile_applied']}`",
        f"- Human review required: `{payload['human_review_required']}`",
        f"- Validation passed: `{payload['validation']['passed']}`",
        "",
        "## Candidate Proposals",
        "",
    ]
    for proposal in payload["candidate_mapping_proposals"]:
        lines.extend(
            [
                f"- `{proposal['source_feature']}` -> `{proposal['runtime_setting']}`",
                f"  proposal: `{proposal['proposal']}`",
                f"  mode: `{proposal['application_mode']}`",
            ]
        )
    lines.extend(
        [
            "",
            "## Blocked Runtime Features",
            "",
        ]
    )
    for feature in payload["blocked_runtime_features"]:
        lines.append(f"- `{feature}`")
    lines.extend(
        [
            "",
            "## Campaign Application Policy",
            "",
            f"- Default voice posture: `{payload['campaign_application_policy']['default_voice_posture']}`",
            f"- Campaign override required: `{payload['campaign_application_policy']['campaign_override_required']}`",
            f"- Protected segments locked: `{payload['campaign_application_policy']['protected_segments_locked']}`",
            f"- Vertical-agnostic core preserved: `{payload['campaign_application_policy']['vertical_agnostic_core_preserved']}`",
            "",
            "## Deferred Reminders",
            "",
        ]
    )
    for reminder in payload["deferred_reminders"]:
        lines.append(f"- `{reminder['reminder_id']}`: {reminder['unlock_condition']}")
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "- Proposal only; no live runtime behavior changes.",
            "- If a private VOICE-030D summary is read, outputs must stay under `data/private/`.",
            "- WhatsApp voice-note import remains deferred until the VOICE-030D review moment.",
        ]
    )
    return "\n".join(lines) + "\n"


def resolve_output_dir(args: argparse.Namespace, *, private_summary: bool, summary_path: Path | None) -> Path:
    if args.out_dir:
        out_dir = resolve_project_path(args.out_dir)
    elif private_summary and summary_path is not None:
        out_dir = summary_path.parent / "voice-031-runtime-mapping"
    else:
        out_dir = DEFAULT_PUBLIC_OUT_DIR

    if private_summary and not is_under(out_dir, PRIVATE_DATA_ROOT):
        raise SystemExit("Refusing to write private-derived VOICE-031 output outside data/private/.")
    return out_dir


def load_review_summary(args: argparse.Namespace, case: dict[str, Any]) -> tuple[dict[str, Any], bool, str, Path | None]:
    if not args.summary_json:
        return case["synthetic_review_summary_fixture"], False, "synthetic_public_fixture", None

    summary_path = resolve_project_path(args.summary_json)
    if not summary_path.is_file():
        raise SystemExit(f"VOICE-031 summary JSON is missing: {project_relative(summary_path)}")

    private_summary = is_under(summary_path, PRIVATE_DATA_ROOT)
    if private_summary and not args.allow_private_review_read:
        raise SystemExit("Refusing to read private VOICE-030D summary without --allow-private-review-read.")
    if not private_summary:
        source_label = "review_summary_json"
    else:
        source_label = "private_voice_030d_review_summary"
    return load_json(summary_path), private_summary, source_label, summary_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a VOICE-031 reviewed feature-to-runtime mapping proposal.")
    parser.add_argument("--case", default=str(CASE_PATH), help="VOICE-031 case/config JSON.")
    parser.add_argument("--summary-json", help="Optional VOICE-030D summary JSON. Private paths require explicit opt-in.")
    parser.add_argument(
        "--allow-private-review-read",
        action="store_true",
        help="Required when --summary-json points under data/private/.",
    )
    parser.add_argument("--out-dir", help="Output directory. Private-derived output must stay under data/private/.")
    parser.add_argument("--print-json", action="store_true", help="Print the mapping payload after writing outputs.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    case_path = resolve_project_path(args.case, CASE_PATH)
    case = load_case(case_path)
    review_summary, private_summary, source_label, summary_path = load_review_summary(args, case)
    out_dir = resolve_output_dir(args, private_summary=private_summary, summary_path=summary_path)
    payload = build_runtime_mapping_plan(
        review_summary,
        source_label=source_label,
        private_review_summary_read=private_summary,
        outputs_stay_under_data_private=is_under(out_dir, PRIVATE_DATA_ROOT),
        deferred_reminders=case.get("deferred_reminders"),
    )

    result_path = out_dir / "results.json"
    report_path = out_dir / "report.md"
    write_json(result_path, payload)
    write_text(report_path, render_report(payload))

    if args.print_json:
        print(json.dumps(payload, indent=2, ensure_ascii=False))
    else:
        print(f"Wrote VOICE-031 JSON result to {project_relative(result_path)}")
        print(f"Wrote VOICE-031 report to {project_relative(report_path)}")


if __name__ == "__main__":
    main()
