#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from speech_interaction import EVALUATION_RUBRIC, apply_speech_interaction


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES_PATH = ROOT / "research" / "experiments" / "cases" / "voice-026-interaction-prosody.json"
DEFAULT_RUN_DIR = ROOT / "research" / "experiments" / "generated" / "VOICE-026-interaction-prosody"
DEFAULT_OUT_PATH = DEFAULT_RUN_DIR / "results.json"
DEFAULT_REPORT_PATH = DEFAULT_RUN_DIR / "report.md"


def resolve_project_path(value: str | None, default: Path) -> Path:
    if not value:
        return default
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    return path


def project_relative_string(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def find_campaign(campaigns: list[dict[str, Any]], campaign_id: str) -> dict[str, Any]:
    for campaign in campaigns:
        if campaign.get("campaign_id") == campaign_id:
            return campaign
    raise KeyError(f"Campaign not found: {campaign_id}")


def run_case(case: dict[str, Any], campaigns: list[dict[str, Any]]) -> dict[str, Any]:
    campaign = find_campaign(campaigns, case["campaign_id"])
    packet = apply_speech_interaction(
        campaign=campaign,
        segments=case["segments"],
        language=case.get("language") or campaign.get("language"),
        seed=case["case_id"],
        customer_state=case.get("customer_state"),
    )
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": packet["language"],
        "speech_interaction": packet,
    }


def aggregate(results: list[dict[str, Any]]) -> dict[str, Any]:
    language_counts: dict[str, int] = {}
    marker_types: dict[str, int] = {}
    pitch_intents: dict[str, int] = {}
    protected_segment_change_count = 0
    unsafe_agreement_marker_count = 0

    for result in results:
        packet = result["speech_interaction"]
        language_counts[result["language"]] = language_counts.get(result["language"], 0) + 1
        protected_segment_change_count += len(packet["validation"]["protected_segment_changes"])
        unsafe_agreement_marker_count += len(packet["validation"]["unsafe_agreement_markers"])
        for marker in packet["interaction_markers"]:
            marker_type = marker.get("marker_type", "unknown")
            pitch_intent = marker.get("pitch_intent", "unknown")
            marker_types[marker_type] = marker_types.get(marker_type, 0) + 1
            pitch_intents[pitch_intent] = pitch_intents.get(pitch_intent, 0) + 1

    return {
        "case_count": len(results),
        "languages": language_counts,
        "marker_count": sum(result["speech_interaction"]["marker_count"] for result in results),
        "marker_types": marker_types,
        "pitch_intents": pitch_intents,
        "validation_passed": sum(1 for result in results if result["speech_interaction"]["validation"]["passed"]),
        "validation_failed": sum(1 for result in results if not result["speech_interaction"]["validation"]["passed"]),
        "protected_segment_change_count": protected_segment_change_count,
        "unsafe_agreement_marker_count": unsafe_agreement_marker_count,
        "provider_calls_made": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
    }


def build_payload(cases_path: Path) -> dict[str, Any]:
    cases_doc = load_json(cases_path)
    results = [run_case(case, cases_doc["campaigns"]) for case in cases_doc["cases"]]
    return {
        "voice_milestone": cases_doc.get("voice_milestone", "VOICE-026"),
        "experiment_scope": cases_doc.get("experiment_scope"),
        "case_source": project_relative_string(cases_path),
        "evaluation_rubric": EVALUATION_RUBRIC,
        "results": results,
        "summary": aggregate(results),
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-026 Interaction Prosody Report",
        "",
        "This report was generated by `scripts/run_voice_026_interaction_prosody.py`.",
        "",
        "VOICE-026 separates listener-style backchannels, lookup acknowledgements, and provider-neutral sales pace cues from the earlier filler-placement layer.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['languages'].get('de', 0)}`",
        f"- English cases: `{summary['languages'].get('en', 0)}`",
        f"- Marker count: `{summary['marker_count']}`",
        f"- Marker types: `{summary['marker_types']}`",
        f"- Pitch intents: `{summary['pitch_intents']}`",
        f"- Protected segment changes: `{summary['protected_segment_change_count']}`",
        f"- Unsafe agreement markers: `{summary['unsafe_agreement_marker_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{summary['voice_cloning_used']}`",
        "",
        "## Interaction Prosody Rule",
        "",
        "- Use short lookup acknowledgements only when a response may need more than about one second of processing.",
        "- Use neutral backchannels for concern, confusion, or unsafe-claim contexts; do not use agreement tokens such as `yes`, `exactly`, `ja`, or `genau` around risky claims.",
        "- Keep sales pace variation provider-neutral and bounded; it is a cue for rhythm, not a rewrite of campaign text.",
        "- Keep campaign questions, disclosures, handoff scripts, hangup lines, and compliance statements exact.",
        "- Keep the layer offline: no TTS provider call, no customer audio upload, and no voice cloning.",
        "",
        "## Listening Rubric",
        "",
    ]
    for key, value in payload["evaluation_rubric"].items():
        lines.append(f"- `{key}`: {value}")

    lines.append("")
    lines.append("## Case Results")

    for result in payload["results"]:
        packet = result["speech_interaction"]
        lines.extend(
            [
                "",
                f"### {result['case_id']}: {result['case_title']}",
                "",
                f"- Campaign: `{result['campaign_id']}`",
                f"- Language: `{result['language']}`",
                f"- Marker count: `{packet['marker_count']}`",
                f"- Unsafe claim context: `{packet['unsafe_claim_context']}`",
                f"- Validation passed: `{packet['validation']['passed']}`",
                f"- TTS text: {packet['tts_text']}",
            ]
        )
        for marker in packet["interaction_markers"]:
            visible = "visible" if marker["visible"] else "non-visible"
            lines.append(
                f"- `{marker['marker_type']}` on `{marker['segment_id']}`: {visible}, placement `{marker['placement']}`, phrase `{marker['marker_text']}`, pause `{marker['pause_ms']}ms`, rate `{marker['rate_multiplier']}`, pitch `{marker['pitch_intent']}`"
            )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the VOICE-026 interaction prosody offline checkpoint.")
    parser.add_argument("--cases", help="Input VOICE-026 case JSON path.")
    parser.add_argument("--out", help="Output JSON path.")
    parser.add_argument("--report-out", help="Output Markdown report path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases, DEFAULT_CASES_PATH)
    out_path = resolve_project_path(args.out, DEFAULT_OUT_PATH)
    report_path = resolve_project_path(args.report_out, DEFAULT_REPORT_PATH)

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))

    print(f"Wrote VOICE-026 results to {project_relative_string(out_path)}")
    print(f"Wrote VOICE-026 report to {project_relative_string(report_path)}")


if __name__ == "__main__":
    main()
