#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from runtime.speech.spoken_text_normalization import apply_spoken_text_normalization


VOICE_MILESTONE = "VOICE-022"
DEFAULT_CASES = ROOT / "research" / "experiments" / "cases" / "voice-022-spoken-text-normalization.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-022-spoken-text-normalization.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-022-spoken-text-normalization-report.md"


def resolve_project_path(path_text: str | None) -> Path | None:
    if not path_text:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def project_relative_string(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def find_campaign(campaigns: list[dict[str, Any]], campaign_id: str) -> dict[str, Any]:
    for campaign in campaigns:
        if campaign.get("campaign_id") == campaign_id:
            return campaign
    raise KeyError(f"Campaign not found: {campaign_id}")


def run_case(case: dict[str, Any], campaigns: list[dict[str, Any]]) -> dict[str, Any]:
    campaign = find_campaign(campaigns, case["campaign_id"])
    packet = apply_spoken_text_normalization(
        campaign=campaign,
        segments=case["segments"],
        language=case.get("language") or campaign.get("language"),
        seed=case["case_id"],
    )
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": packet["language"],
        "expected": case.get("expected", {}),
        "spoken_text_normalization": packet,
    }


def aggregate(results: list[dict[str, Any]]) -> dict[str, Any]:
    language_counts: dict[str, int] = {}
    protected_segment_change_count = 0
    profile_styles = set()

    for result in results:
        packet = result["spoken_text_normalization"]
        language_counts[result["language"]] = language_counts.get(result["language"], 0) + 1
        profile_styles.add(packet["profile"]["style"])
        protected_segment_change_count += len(packet["validation"]["protected_segment_changes"])

    return {
        "case_count": len(results),
        "languages": language_counts,
        "profile_styles": sorted(profile_styles),
        "normalization_count": sum(result["spoken_text_normalization"]["normalization_count"] for result in results),
        "eligible_segment_count": sum(result["spoken_text_normalization"]["eligible_segment_count"] for result in results),
        "protected_segment_count": sum(result["spoken_text_normalization"]["protected_segment_count"] for result in results),
        "protected_segment_change_count": protected_segment_change_count,
        "validation_passed": sum(1 for result in results if result["spoken_text_normalization"]["validation"]["passed"]),
        "validation_failed": sum(1 for result in results if not result["spoken_text_normalization"]["validation"]["passed"]),
        "provider_calls_made": False,
        "requires_api_key": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-022 Spoken Text Normalization Report",
        "",
        "This report was generated by `scripts/run_voice_022_spoken_text_normalization.py`.",
        "",
        "VOICE-022 is local, text-only, and provider-neutral. It prepares safer spoken TTS wording for eligible freeform segments without changing protected campaign or compliance text.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['languages'].get('de', 0)}`",
        f"- English cases: `{summary['languages'].get('en', 0)}`",
        f"- Profile styles: `{', '.join(summary['profile_styles'])}`",
        f"- Normalizations: `{summary['normalization_count']}`",
        f"- Eligible segments: `{summary['eligible_segment_count']}`",
        f"- Protected segments: `{summary['protected_segment_count']}`",
        f"- Protected segment changes: `{summary['protected_segment_change_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        "",
        "## Boundary",
        "",
        "English contractions and German spoken equivalents are allowed only in eligible freeform speech. Exact campaign questions, required disclosures, insurance/legal/medical boundaries, handoff scripts, hangup lines, and appointment confirmations stay unchanged.",
        "",
        "## Case Results",
    ]

    for result in payload["results"]:
        packet = result["spoken_text_normalization"]
        lines.extend(
            [
                "",
                f"### {result['case_id']}: {result['case_title']}",
                "",
                f"- Campaign: `{result['campaign_id']}`",
                f"- Language: `{result['language']}`",
                f"- Normalization count: `{packet['normalization_count']}`",
                f"- Eligible segments: `{packet['eligible_segment_count']}`",
                f"- Protected segments: `{packet['protected_segment_count']}`",
                f"- Validation passed: `{packet['validation']['passed']}`",
                f"- TTS text: {packet['tts_text']}",
            ]
        )
        for operation in packet["normalizations"]:
            lines.append(
                f"- `{operation['rule_id']}` on `{operation['segment_id']}`: `{operation['before']}` -> `{operation['after']}`"
            )
    return "\n".join(lines) + "\n"


def build_payload(cases_path: Path) -> dict[str, Any]:
    case_file = load_json(cases_path)
    campaigns = case_file["campaigns"]
    results = [run_case(case, campaigns) for case in case_file["cases"]]
    return {
        "voice_milestone": VOICE_MILESTONE,
        "experiment_scope": case_file.get("experiment_scope"),
        "case_file": project_relative_string(cases_path),
        "summary": aggregate(results),
        "runtime_boundary": {
            "text_only": True,
            "provider_calls_made": False,
            "requires_api_key": False,
            "customer_audio_uploaded": False,
            "voice_cloning_used": False,
            "safe_default": "local deterministic spoken-text normalization only",
        },
        "results": results,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run VOICE-022 spoken-text normalization cases.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES), help="VOICE-022 case file.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="JSON output path.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Markdown report output path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    if cases_path is None or out_path is None or report_path is None:
        raise SystemExit("Cases, output, and report paths are required.")

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))
    print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
