#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from speech_naturalness import apply_speech_naturalness


ROOT = Path(__file__).resolve().parents[1]
VOICE_MILESTONE = "VOICE-012"
DEFAULT_CASES = ROOT / "research" / "experiments" / "cases" / "voice-012-speech-naturalness.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-012-speech-naturalness.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-012-speech-naturalness-report.md"


def resolve_project_path(path_text: str | None) -> Path | None:
    if not path_text:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def project_relative_string(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def find_campaign(campaigns: list[dict[str, Any]], campaign_id: str) -> dict[str, Any]:
    for campaign in campaigns:
        if campaign.get("campaign_id") == campaign_id:
            return campaign
    raise KeyError(f"Campaign not found: {campaign_id}")


def run_case(case: dict[str, Any], campaigns: list[dict[str, Any]]) -> dict[str, Any]:
    campaign = find_campaign(campaigns, case["campaign_id"])
    packet = apply_speech_naturalness(
        campaign=campaign,
        segments=case["segments"],
        language=case.get("language") or campaign.get("language"),
        seed=case["case_id"],
    )
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": packet["language"],
        "expected": case.get("expected", {}),
        "speech_naturalness": packet,
    }


def aggregate(results: list[dict[str, Any]]) -> dict[str, Any]:
    case_count = len(results)
    filler_count = sum(result["speech_naturalness"]["filler_count"] for result in results)
    protected_segment_count = sum(result["speech_naturalness"]["protected_segment_count"] for result in results)
    eligible_segment_count = sum(result["speech_naturalness"]["eligible_segment_count"] for result in results)
    passed_count = sum(1 for result in results if result["speech_naturalness"]["validation"]["passed"])
    language_counts: dict[str, int] = {}
    for result in results:
        language_counts[result["language"]] = language_counts.get(result["language"], 0) + 1
    return {
        "case_count": case_count,
        "languages": language_counts,
        "filler_count": filler_count,
        "eligible_segment_count": eligible_segment_count,
        "protected_segment_count": protected_segment_count,
        "validation_passed": passed_count,
        "validation_failed": case_count - passed_count,
        "provider_calls_made": False,
        "requires_api_key": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-012 Speech Naturalness Report",
        "",
        "This report was generated by `scripts/run_voice_012_speech_naturalness.py`.",
        "",
        "VOICE-012 is text-only. It does not call a TTS provider, require an API key, upload customer audio, or use voice cloning.",
        "",
        "## Purpose",
        "",
        "Add a campaign-configurable speech naturalness layer that can make agent speech less machine-perfect while preserving campaign and compliance text exactly.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['languages'].get('de', 0)}`",
        f"- English cases: `{summary['languages'].get('en', 0)}`",
        f"- Fillers inserted: `{summary['filler_count']}`",
        f"- Eligible freeform segments: `{summary['eligible_segment_count']}`",
        f"- Protected segments: `{summary['protected_segment_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        "",
        "## Segment Rule",
        "",
        "Fillers may appear only in eligible freeform speech such as empathy, objection handling, transitions, explanations, or clarifications.",
        "",
        "Fillers are blocked in campaign qualification questions, company scripts, required disclosures, compliance statements, insurance/coverage boundaries, do-not-call confirmations, hang-up lines, appointment confirmations, and sensitive escalations.",
        "",
        "## Case Results",
    ]

    for result in payload["results"]:
        packet = result["speech_naturalness"]
        validation = packet["validation"]
        lines.extend(
            [
                "",
                f"### {result['case_id']}: {result['case_title']}",
                "",
                f"- Campaign: `{result['campaign_id']}`",
                f"- Language: `{result['language']}`",
                f"- Fillers inserted: `{packet['filler_count']}`",
                f"- Filler quota: `{packet['filler_quota']}`",
                f"- Eligible segments: `{packet['eligible_segment_count']}`",
                f"- Protected segments: `{packet['protected_segment_count']}`",
                f"- Validation passed: `{validation['passed']}`",
                f"- TTS text: {packet['tts_text']}",
            ]
        )
        for segment in packet["output_segments"]:
            if segment["protected_reason"] or segment["filler_inserted"]:
                lines.extend(
                    [
                        f"- Segment `{segment['segment_id']}` type `{segment['segment_type']}`:",
                        f"  protected reason: `{segment['protected_reason'] or 'none'}`; filler: `{segment['filler_inserted'] or 'none'}`",
                    ]
                )
    return "\n".join(lines) + "\n"


def build_payload(cases_path: Path) -> dict[str, Any]:
    case_file = load_json(cases_path)
    campaigns = case_file["campaigns"]
    results = [run_case(case, campaigns) for case in case_file["cases"]]
    return {
        "voice_milestone": VOICE_MILESTONE,
        "experiment_scope": case_file.get("experiment_scope"),
        "case_file": project_relative_string(cases_path),
        "summary": aggregate(results),
        "runtime_boundary": {
            "text_only": True,
            "provider_calls_made": False,
            "requires_api_key": False,
            "customer_audio_uploaded": False,
            "voice_cloning_used": False,
            "safe_default": "local deterministic transformation only",
        },
        "results": results,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run VOICE-012 segment-aware speech naturalness cases.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES), help="VOICE-012 case file.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="JSON output path.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Markdown report output path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    if cases_path is None or out_path is None or report_path is None:
        raise SystemExit("Cases, output, and report paths are required.")

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))
    print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
