#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from generate_guarded_response import build_guarded_response_packet
from realtime_turn_cli import find_campaign
from run_realtime_turn_simulation import load_realtime_cases
from runtime_voice_delivery import attach_runtime_voice_delivery


ROOT = Path(__file__).resolve().parents[1]
VOICE_MILESTONE = "VOICE-037"
DEFAULT_CASES = ROOT / "research" / "experiments" / "cases" / "voice-037-emotion-smoothing.json"
DEFAULT_OUT_DIR = ROOT / "research" / "experiments" / "generated" / "VOICE-037-emotion-smoothing"


def resolve_project_path(path_text: str | None, default: Path | None = None) -> Path:
    if path_text:
        path = Path(path_text)
        return path if path.is_absolute() else ROOT / path
    if default is None:
        raise SystemExit("Missing required path.")
    return default


def project_relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build_case_result(case: dict[str, Any], campaign: dict[str, Any], provider: str) -> dict[str, Any]:
    guarded_packet = build_guarded_response_packet(
        campaign=campaign,
        stage=case["stage"],
        input_type="speech-final",
        transcript=case["transcript"],
        silence_count=int(case.get("silence_count", 0)),
        candidate_response_override=case.get("candidate_response"),
    )
    packet = attach_runtime_voice_delivery(guarded_packet, campaign, provider_key=provider)
    delivery = packet["voice_delivery"]
    smoothing = delivery["voice_emotion_smoothing"]
    provider_rendering = delivery["provider_rendering"]
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": delivery["language"],
        "expected_emotion_smoothing": case["expected_emotion_smoothing"],
        "segment_type": delivery["segments"][0]["segment_type"],
        "final_response_unchanged": delivery["final_response_unchanged"],
        "emotion_smoothing": smoothing,
        "provider_rendering": {
            "provider_key": provider_rendering["provider_key"],
            "rendered_text": provider_rendering["rendered_text"],
            "voice_settings": provider_rendering.get("voice_settings") or {},
            "provider_tag_count": provider_rendering.get("provider_tag_count", 0),
        },
        "validation": {
            "passed": smoothing["validation"]["passed"] and delivery["validation"]["passed"],
            "runtime_voice_validation_passed": delivery["validation"]["passed"],
            "emotion_smoothing_validation_passed": smoothing["validation"]["passed"],
        },
    }


def aggregate(cases: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "case_count": len(cases),
        "german_cases": sum(1 for case in cases if case["language"] == "de"),
        "english_cases": sum(1 for case in cases if case["language"] == "en"),
        "transition_smoothed_cases": sum(1 for case in cases if case["emotion_smoothing"]["transition_smoothing_applied"]),
        "blocked_overemotional_cue_cases": sum(
            1 for case in cases if case["emotion_smoothing"]["blocked_overemotional_cue_count"] > 0
        ),
        "protected_case_count": sum(1 for case in cases if not case["emotion_smoothing"]["eligible_for_smoothing"]),
        "validation_passed": sum(1 for case in cases if case["validation"]["passed"]),
        "provider_calls_made": False,
        "requires_api_key": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
        "generated_audio_created": False,
        "quality_claim_allowed": False,
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-037 Emotion Transition Smoothing Report",
        "",
        "This report was generated by `scripts/run_voice_037_emotion_smoothing.py`.",
        "",
        "VOICE-037 is offline and no-key. It adds emotional inertia to provider-facing delivery so the agent does not jump too sharply between vocal moods.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['german_cases']}`",
        f"- English cases: `{summary['english_cases']}`",
        f"- Transition-smoothed cases: `{summary['transition_smoothed_cases']}`",
        f"- Blocked over-emotional cue cases: `{summary['blocked_overemotional_cue_cases']}`",
        f"- Protected cases: `{summary['protected_case_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{summary['voice_cloning_used']}`",
        "",
        "## Case Results",
        "",
    ]
    for case in payload["cases"]:
        smoothing = case["emotion_smoothing"]
        settings = case["provider_rendering"]["voice_settings"]
        lines.extend(
            [
                f"### {case['case_id']}: {case['case_title']}",
                "",
                f"- Language: `{case['language']}`",
                f"- Segment type: `{case['segment_type']}`",
                f"- Expected smoothing: `{case['expected_emotion_smoothing']}`",
                f"- Eligible for smoothing: `{smoothing['eligible_for_smoothing']}`",
                f"- Transition smoothing applied: `{smoothing['transition_smoothing_applied']}`",
                f"- Detected transitions: `{smoothing['detected_transition_count']}`",
                f"- Smoothed transitions: `{smoothing['smoothed_transition_count']}`",
                f"- Blocked over-emotional cues: `{smoothing['blocked_overemotional_cue_count']}`",
                f"- Stability: `{settings.get('stability', 'not-set')}`",
                f"- Style: `{settings.get('style', 'not-set')}`",
                f"- Speed: `{settings.get('speed', 'not-set')}`",
                f"- Validation passed: `{case['validation']['passed']}`",
                f"- Rendered text: {case['provider_rendering']['rendered_text']}",
                "",
            ]
        )
    lines.extend(
        [
            "## Boundary",
            "",
            "- No provider calls.",
            "- No generated audio.",
            "- No customer/private audio.",
            "- No voice cloning.",
            "- No final-response rewrite.",
            "- No rendered-word rewrite.",
            "- Speed is preserved by the emotion smoothing layer.",
            "- Protected campaign, compliance, handoff, hangup, and do-not-call text stays exact.",
        ]
    )
    return "\n".join(lines) + "\n"


def build_payload(cases_path: Path) -> dict[str, Any]:
    config = load_json(cases_path)
    source_cases_path = resolve_project_path(config["source_cases"])
    campaigns, _runtime_cases = load_realtime_cases(source_cases_path)
    provider = config.get("provider", "elevenlabs")
    cases = [
        build_case_result(case, find_campaign(campaigns, case["campaign_id"]), provider)
        for case in config["runtime_cases"]
    ]
    return {
        "voice_milestone": VOICE_MILESTONE,
        "experiment_scope": config["experiment_scope"],
        "case_file": project_relative(cases_path),
        "source_cases": project_relative(source_cases_path),
        "emotion_smoothing_policy": config["emotion_smoothing_policy"],
        "summary": aggregate(cases),
        "runtime_boundary": {
            "offline_preview_only": True,
            "provider_calls_made": False,
            "requires_api_key": False,
            "customer_audio_uploaded": False,
            "voice_cloning_used": False,
            "generated_audio_created": False,
            "quality_claim_allowed_without_human_rating": False,
        },
        "cases": cases,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run VOICE-037 offline emotion-transition smoothing.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES), help="VOICE-037 case/config file.")
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR), help="Output directory for results.json and report.md.")
    parser.add_argument("--print-json", action="store_true", help="Print the full payload after writing artifacts.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases, DEFAULT_CASES)
    out_dir = resolve_project_path(args.out_dir, DEFAULT_OUT_DIR)
    payload = build_payload(cases_path)
    write_json(out_dir / "results.json", payload)
    write_text(out_dir / "report.md", render_report(payload))
    if args.print_json:
        print(json.dumps(payload, indent=2, ensure_ascii=False))
    else:
        print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
