#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from provider_prosody_rendering import render_case


ROOT = Path(__file__).resolve().parents[1]
VOICE_MILESTONE = "VOICE-016"
DEFAULT_CASES = ROOT / "research" / "experiments" / "cases" / "voice-016-provider-prosody-rendering.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-016-provider-prosody-rendering.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-016-provider-prosody-rendering-report.md"


def resolve_project_path(path_text: str | None) -> Path | None:
    if not path_text:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def project_relative_string(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def provider_counts(cases: list[dict[str, Any]], provider_key: str, count_key: str) -> dict[str, int]:
    counts = {"emphasis": 0, "pause": 0, "pitch": 0, "rate": 0, "stretch": 0}
    for case in cases:
        variant = next(item for item in case["provider_variants"] if item["provider_key"] == provider_key)
        for cue_type, count in variant[count_key].items():
            counts[cue_type] = counts.get(cue_type, 0) + count
    return counts


def aggregate(cases: list[dict[str, Any]], providers: list[dict[str, Any]]) -> dict[str, Any]:
    provider_keys = [provider["provider_key"] for provider in providers]
    language_counts: dict[str, int] = {}
    for case in cases:
        language_counts[case["language"]] = language_counts.get(case["language"], 0) + 1

    return {
        "case_count": len(cases),
        "languages": language_counts,
        "provider_count": len(providers),
        "providers": provider_keys,
        "provider_mapped_cue_counts": {
            provider_key: provider_counts(cases, provider_key, "mapped_cue_counts") for provider_key in provider_keys
        },
        "provider_unsupported_cue_counts": {
            provider_key: provider_counts(cases, provider_key, "unsupported_cue_counts") for provider_key in provider_keys
        },
        "protected_segment_provider_tag_count": sum(
            variant["protected_segment_provider_tag_count"]
            for case in cases
            for variant in case["provider_variants"]
        ),
        "validation_passed": sum(1 for case in cases if case["validation"]["passed"]),
        "validation_failed": sum(1 for case in cases if not case["validation"]["passed"]),
        "provider_calls_made": False,
        "requires_api_key": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
        "generated_audio_created": False,
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-016 Provider Prosody Rendering Report",
        "",
        "This report was generated by `scripts/run_voice_016_provider_prosody_rendering.py`.",
        "",
        "VOICE-016 is offline. It renders VOICE-015 prosody cues into provider-specific text/request previews and makes no provider calls.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['languages'].get('de', 0)}`",
        f"- English cases: `{summary['languages'].get('en', 0)}`",
        f"- Providers: `{', '.join(summary['providers'])}`",
        f"- Protected-segment provider tags: `{summary['protected_segment_provider_tag_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Requires API key: `{summary['requires_api_key']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        "",
        "## Provider Mapping",
        "",
    ]
    for provider in payload["providers"]:
        key = provider["provider_key"]
        lines.extend(
            [
                f"### {provider['provider_name']}",
                "",
                f"- Rendering mode: `{provider['provider_rendering_mode']}`",
                f"- Supported cues in this checkpoint: `{', '.join(provider['supported_cues'])}`",
                f"- Unsupported cues recorded, not forced: `{', '.join(provider['unsupported_cues'])}`",
                f"- Mapped cue counts: `{summary['provider_mapped_cue_counts'][key]}`",
                f"- Unsupported cue counts: `{summary['provider_unsupported_cue_counts'][key]}`",
                "",
            ]
        )
    lines.append("## Case Results")
    for case in payload["cases"]:
        lines.extend(
            [
                "",
                f"### {case['case_id']}: {case['case_title']}",
                "",
                f"- Language: `{case['language']}`",
                f"- Prosody cues: `{case['prosody_cue_count']}`",
                f"- Plain text: {case['plain_text']}",
            ]
        )
        for variant in case["provider_variants"]:
            lines.extend(
                [
                    f"- {variant['provider_name']} rendered text: {variant['rendered_text']}",
                    f"- {variant['provider_name']} mapped: `{variant['mapped_cue_counts']}`",
                    f"- {variant['provider_name']} unsupported: `{variant['unsupported_cue_counts']}`",
                ]
            )
    return "\n".join(lines) + "\n"


def build_payload(cases_path: Path) -> dict[str, Any]:
    config = load_json(cases_path)
    source_path = resolve_project_path(config["source_artifact"])
    if source_path is None:
        raise SystemExit("VOICE-016 source artifact could not be resolved.")
    source = load_json(source_path)
    providers = config["providers"]
    cases = [render_case(result, providers) for result in source["results"]]
    return {
        "voice_milestone": VOICE_MILESTONE,
        "experiment_scope": config["experiment_scope"],
        "case_file": project_relative_string(cases_path),
        "source_artifact": project_relative_string(source_path),
        "providers": providers,
        "rendering_policy": config["rendering_policy"],
        "summary": aggregate(cases, providers),
        "runtime_boundary": {
            "offline_preview_only": True,
            "provider_calls_made": False,
            "requires_api_key": False,
            "customer_audio_uploaded": False,
            "voice_cloning_used": False,
            "generated_audio_created": False,
        },
        "cases": cases,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render VOICE-015 prosody cues into provider-specific offline previews.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES), help="VOICE-016 rendering case file.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="JSON output path.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Markdown report output path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    if cases_path is None or out_path is None or report_path is None:
        raise SystemExit("Cases, output, and report paths are required.")

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))
    print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
