#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

from generate_voice_response import resolve_project_path
from run_browser_speech_demo import DEFAULT_CASES_PATH, build_browser_decision_packet
from voice_interruption_policy import classify_interruption_candidate, interruption_policy_metadata


ROOT = Path(__file__).resolve().parents[1]
VOICE_MILESTONE = "VOICE-006"
DEFAULT_RESULTS_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-006-interruption-results.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-006-interruption-report.md"
CURRENT_AGENT_RESPONSE = (
    "That makes sense. Is your bigger concern the monthly price, the contract terms, "
    "or whether reviewing options is worth your time?"
)

INTERRUPTION_CASES = [
    {
        "case_id": "VOICE-006-C01",
        "case_title": "Background noise must not stop the agent",
        "audio_event_type": "background-noise",
        "transcript": "",
    },
    {
        "case_id": "VOICE-006-C02",
        "case_title": "Likely echo must not stop the agent",
        "audio_event_type": "speech-interim",
        "transcript": "Is your bigger concern the monthly price",
    },
    {
        "case_id": "VOICE-006-C03",
        "case_title": "Short ambiguous interruption asks clarification",
        "audio_event_type": "speech-final",
        "transcript": "Huh?",
    },
    {
        "case_id": "VOICE-006-C04",
        "case_title": "Clear customer question becomes a new turn",
        "audio_event_type": "speech-final",
        "transcript": "What does that mean?",
    },
    {
        "case_id": "VOICE-006-C05",
        "case_title": "Stop request interrupts and ends call",
        "audio_event_type": "speech-final",
        "transcript": "Stop calling me.",
    },
    {
        "case_id": "VOICE-006-C06",
        "case_title": "Human request interrupts and escalates",
        "audio_event_type": "speech-final",
        "transcript": "Please have a real person call me.",
    },
]


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def run_case(case: dict, cases_path: Path) -> dict:
    interruption_decision = classify_interruption_candidate(
        transcript=case["transcript"],
        agent_response=CURRENT_AGENT_RESPONSE,
        audio_event_type=case["audio_event_type"],
        agent_is_speaking=True,
    )
    voice_packet = None
    if interruption_decision["send_to_agent_core"]:
        voice_packet = build_browser_decision_packet(
            transcript=case["transcript"],
            campaign_id="campaign-prod-005-b2c-telecom",
            stage="relevance-check",
            input_type="speech-final",
            silence_count=0,
            cases_path=cases_path,
        )
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "audio_event_type": case["audio_event_type"],
        "transcript": case["transcript"],
        "agent_response_under_playback": CURRENT_AGENT_RESPONSE,
        "interruption_decision": interruption_decision,
        "voice_packet": voice_packet,
    }


def summarize(cases: list[dict]) -> dict:
    return {
        "case_count": len(cases),
        "confirmed_interruptions": sum(1 for case in cases if case["interruption_decision"]["interruption_confirmed"]),
        "false_interruptions_blocked": sum(
            1
            for case in cases
            if case["interruption_decision"]["interruption_type"] in {"noise_or_no_transcript", "likely_echo"}
            and not case["interruption_decision"]["interruption_confirmed"]
        ),
        "clarification_cases": sum(
            1
            for case in cases
            if case["interruption_decision"]["agent_speech_action"] == "pause-and-ask-clarification"
        ),
        "sent_to_agent_core": sum(1 for case in cases if case["interruption_decision"]["send_to_agent_core"]),
    }


def render_report(payload: dict) -> str:
    lines = [
        "# VOICE-006 Safe Interruption Report",
        "",
        "This report was generated by `scripts/run_voice_006_interruption_simulation.py`.",
        "",
        "Raw audio alone does not cancel agent speech.",
        "",
        "Short ambiguous interruption asks clarification instead of being sent directly to the sales core.",
        "",
        "Likely echo is ignored so the agent does not interrupt itself.",
        "",
        "## Summary",
        "",
        f"- Cases: `{payload['summary']['case_count']}`",
        f"- Confirmed interruptions: `{payload['summary']['confirmed_interruptions']}`",
        f"- False interruptions blocked: `{payload['summary']['false_interruptions_blocked']}`",
        f"- Clarification cases: `{payload['summary']['clarification_cases']}`",
        f"- Sent to agent core: `{payload['summary']['sent_to_agent_core']}`",
        "",
        "## Case Results",
        "",
    ]
    for case in payload["cases"]:
        decision = case["interruption_decision"]
        call_control = None
        if case["voice_packet"] is not None:
            call_control = case["voice_packet"]["response_packet"]["decision"]["call_control"]
        lines.extend(
            [
                f"### {case['case_id']}: {case['case_title']}",
                "",
                f"- Interruption type: `{decision['interruption_type']}`",
                f"- Confirmed: `{decision['interruption_confirmed']}`",
                f"- Agent speech action: `{decision['agent_speech_action']}`",
                f"- Send to agent core: `{decision['send_to_agent_core']}`",
                f"- Call control: `{call_control or 'not sent'}`",
                f"- Rationale: {decision['rationale']}",
                "",
            ]
        )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run VOICE-006 safe interruption simulation.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES_PATH), help="Campaign wrapper case file to load.")
    parser.add_argument("--out", default=str(DEFAULT_RESULTS_OUT), help="Path to write JSON results.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Path to write Markdown report.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    cases = [run_case(case, cases_path) for case in INTERRUPTION_CASES]
    payload = {
        "voice_milestone": VOICE_MILESTONE,
        "policy": interruption_policy_metadata(),
        "server_started": False,
        "requires_api_key": False,
        "summary": summarize(cases),
        "cases": cases,
    }
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))
    print(json.dumps(payload, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
