#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from personal_speech_profile import build_profile, samples_from_case, samples_from_directory


ROOT = Path(__file__).resolve().parents[1]
CASE_PATH = ROOT / "research" / "experiments" / "cases" / "voice-029-local-speech-profile-learning.json"
DEFAULT_GENERATED_DIR = ROOT / "research" / "experiments" / "generated" / "VOICE-029-local-speech-profile-learning"
DEFAULT_GENERATED_OUT = DEFAULT_GENERATED_DIR / "results.json"
DEFAULT_GENERATED_REPORT = DEFAULT_GENERATED_DIR / "report.md"
PRIVATE_ROOT = ROOT / "data" / "private"
DEFAULT_PRIVATE_INPUT = PRIVATE_ROOT / "tarik-speech-samples" / "transcripts-redacted"
DEFAULT_PRIVATE_OUT = PRIVATE_ROOT / "tarik-speech-samples" / "derived" / "local-speech-profile-draft.json"
DEFAULT_PRIVATE_REPORT = PRIVATE_ROOT / "tarik-speech-samples" / "derived" / "local-speech-profile-draft.md"


def resolve_project_path(value: str | None, default: Path) -> Path:
    if not value:
        return default
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    return path


def is_under(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def project_relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def render_report(payload: dict[str, Any]) -> str:
    lines = [
        "# VOICE-029 Local Speech Profile Report",
        "",
        "This report was generated by `scripts/run_voice_029_local_speech_profile.py`.",
        "",
        "VOICE-029 extracts abstract speech-pattern signals only. It does not export raw transcripts, call providers, read raw audio, or clone voices.",
        "",
        "## Summary",
        "",
        f"- Source mode: `{payload['source_mode']}`",
        f"- Samples: `{payload['summary']['sample_count']}`",
        f"- Languages: `{payload['summary']['languages']}`",
        f"- Safe public artifact: `{payload['summary']['safe_public_artifact']}`",
        f"- Private input read: `{payload['privacy_boundary']['private_input_read']}`",
        f"- Raw audio read: `{payload['privacy_boundary']['raw_audio_read']}`",
        f"- Provider calls made: `{payload['privacy_boundary']['provider_calls_made']}`",
        f"- Voice cloning used: `{payload['privacy_boundary']['voice_cloning_used']}`",
        f"- Raw transcript exported: `{payload['privacy_boundary']['raw_transcript_exported']}`",
        f"- Human review required before runtime use: `{payload['privacy_boundary']['human_review_required_before_runtime_use']}`",
        "",
        "## Abstract Pattern Profile",
        "",
    ]
    for language, profile in payload["pattern_profile"]["languages"].items():
        lines.extend(
            [
                f"### {language}",
                "",
                f"- Samples: `{profile['sample_count']}`",
                f"- Words: `{profile['word_count']}`",
                f"- Average words per sentence: `{profile['avg_words_per_sentence']}`",
                f"- Filler marker count: `{profile['filler_marker_count']}`",
                f"- Filler rate per 100 words: `{profile['filler_rate_per_100_words']}`",
                f"- Repair marker count: `{profile['repair_marker_count']}`",
                f"- Contraction count: `{profile['contraction_count']}`",
                f"- Pause marker count: `{profile['pause_marker_count']}`",
                f"- Top filler markers: `{profile['top_filler_markers']}`",
                f"- Top repair markers: `{profile['top_repair_markers']}`",
                "",
            ]
        )
    proposal = payload["runtime_profile_proposal"]
    lines.extend(
        [
            "## Runtime Proposal Boundary",
            "",
            f"- Apply to runtime by default: `{proposal['apply_to_runtime_by_default']}`",
            f"- Requires human review: `{proposal['requires_human_review']}`",
            f"- Suggested filler intensity: `{proposal['speech_realism']['suggested_filler_intensity']}`",
            f"- Preferred placement: `{proposal['speech_realism']['preferred_placement']}`",
            f"- Suggested max imperfections per response: `{proposal['speech_imperfections']['suggested_max_imperfections_per_response']}`",
            "",
            "No raw sample text is included in this report.",
        ]
    )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run VOICE-029 local-only speech-pattern profile extraction.")
    parser.add_argument("--case", default=str(CASE_PATH), help="VOICE-029 case/config JSON.")
    parser.add_argument("--input-dir", help="Optional directory of redacted .txt/.md transcripts or notes.")
    parser.add_argument(
        "--allow-private-read",
        action="store_true",
        help="Required when --input-dir is inside data/private. Output must also stay inside data/private.",
    )
    parser.add_argument("--out", help="Output JSON path.")
    parser.add_argument("--report-out", help="Output Markdown report path.")
    return parser.parse_args()


def build_payload(args: argparse.Namespace) -> tuple[dict[str, Any], Path, Path]:
    case_path = resolve_project_path(args.case, CASE_PATH)
    case = load_json(case_path)
    input_dir = resolve_project_path(args.input_dir, DEFAULT_PRIVATE_INPUT) if args.input_dir else None

    if input_dir is None:
        samples = samples_from_case(case)
        private_input_read = False
        source_mode = "synthetic_fixture"
        out_path = resolve_project_path(args.out, DEFAULT_GENERATED_OUT)
        report_path = resolve_project_path(args.report_out, DEFAULT_GENERATED_REPORT)
    else:
        private_input = is_under(input_dir, PRIVATE_ROOT)
        if private_input and not args.allow_private_read:
            raise SystemExit(
                "Refusing to read data/private without --allow-private-read. "
                "Use redacted transcripts only and keep outputs under data/private."
            )
        if not input_dir.is_dir():
            raise SystemExit(f"Input directory does not exist: {input_dir}")
        private_input_read = private_input
        source_mode = "private_redacted_transcripts" if private_input else "local_text_directory"
        out_path = resolve_project_path(args.out, DEFAULT_PRIVATE_OUT if private_input else DEFAULT_GENERATED_OUT)
        report_path = resolve_project_path(
            args.report_out,
            DEFAULT_PRIVATE_REPORT if private_input else DEFAULT_GENERATED_REPORT,
        )
        if private_input and (not is_under(out_path, PRIVATE_ROOT) or not is_under(report_path, PRIVATE_ROOT)):
            raise SystemExit("Private input outputs must stay under data/private until a later reviewed export checkpoint.")
        samples = samples_from_directory(input_dir)

    payload = build_profile(samples, source_mode=source_mode, private_input_read=private_input_read)
    payload["private_workspace"] = case["private_workspace"]
    return payload, out_path, report_path


def main() -> None:
    args = parse_args()
    payload, out_path, report_path = build_payload(args)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))
    print(f"Wrote VOICE-029 results to {project_relative(out_path)}")
    print(f"Wrote VOICE-029 report to {project_relative(report_path)}")


if __name__ == "__main__":
    main()
