#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
VOICE_MILESTONE = "VOICE-020"
DEFAULT_CASES = ROOT / "research" / "experiments" / "cases" / "voice-020-elevenlabs-voice-design.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-020-elevenlabs-voice-design.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-020-elevenlabs-voice-design-report.md"


def resolve_project_path(path_text: str | None) -> Path | None:
    if not path_text:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def project_relative_string(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def load_available_sources(source_artifacts: list[str]) -> list[dict[str, Any]]:
    available = []
    for source in source_artifacts:
        path = resolve_project_path(source)
        if path is None:
            continue
        available.append(
            {
                "path": project_relative_string(path),
                "exists": path.exists(),
                "used_as_private_data_source": False,
            }
        )
    return available


def summarize(config: dict[str, Any], available_sources: list[dict[str, Any]]) -> dict[str, Any]:
    languages = sorted({profile["language"] for profile in config["voice_design_profiles"]})
    return {
        "voice_design_profile_count": len(config["voice_design_profiles"]),
        "languages": languages,
        "voice_design_ui_candidate_count": len(config["voice_design_ui_candidates"]),
        "voice_remixing_prompt_count": len(config["voice_remixing_prompts"]),
        "settings_candidate_count": len(config["settings_matrix"]),
        "emotional_delivery_bundle_count": len(config["emotional_delivery_bundles"]),
        "protected_segment_type_count": len(config["protected_text_rules"]["segment_types"]),
        "official_source_count": len(config["official_sources"]),
        "source_artifacts_available": sum(1 for source in available_sources if source["exists"]),
        "provider_calls_made": False,
        "requires_api_key": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
        "generated_audio_created": False,
        "quality_claim_allowed": False,
        "private_audio_uploaded": False,
        "private_audio_copied_to_generated_artifacts": False,
        "ready_for_elevenlabs_dashboard_voice_creation": True,
    }


def build_dashboard_steps(config: dict[str, Any]) -> list[str]:
    profile_ids = ", ".join(profile["profile_id"] for profile in config["voice_design_profiles"])
    ui_candidate_ids = ", ".join(candidate["candidate_id"] for candidate in config["voice_design_ui_candidates"])
    remix_prompt_ids = ", ".join(prompt["remix_prompt_id"] for prompt in config["voice_remixing_prompts"])
    candidate_ids = ", ".join(candidate["candidate_id"] for candidate in config["settings_matrix"])
    return [
        f"Create or select voice candidates for profiles: {profile_ids}.",
        "Use synthetic preview text only; do not upload private call audio or customer voices.",
        f"Try Voice Design UI candidates first: {ui_candidate_ids}.",
        f"Remix selected voices with prompts: {remix_prompt_ids}.",
        f"Test voice settings candidates: {candidate_ids}.",
        "Listen first to openings, then objection handling, then protected-text clarity.",
        "Keep human ratings separate from provider latency and response-content quality.",
        "Promote a voice only after English and German samples both pass the listening rubric.",
    ]


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-020 ElevenLabs Voice Design Report",
        "",
        "This report was generated by `scripts/run_voice_020_elevenlabs_voice_design.py`.",
        "",
        "VOICE-020 is offline and no-key. It does not create audio, call ElevenLabs, upload private audio, or clone voices.",
        "",
        "## Summary",
        "",
        f"- Voice design profiles: `{summary['voice_design_profile_count']}`",
        f"- Languages: `{', '.join(summary['languages'])}`",
        f"- Voice Design UI candidates: `{summary['voice_design_ui_candidate_count']}`",
        f"- Voice Remixing prompts: `{summary['voice_remixing_prompt_count']}`",
        f"- Settings candidates: `{summary['settings_candidate_count']}`",
        f"- Emotional delivery bundles: `{summary['emotional_delivery_bundle_count']}`",
        f"- Protected segment types: `{summary['protected_segment_type_count']}`",
        f"- Official sources: `{summary['official_source_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Requires API key: `{summary['requires_api_key']}`",
        f"- Private audio uploaded: `{summary['private_audio_uploaded']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{summary['voice_cloning_used']}`",
        f"- Generated audio created: `{summary['generated_audio_created']}`",
        f"- Quality claim allowed: `{summary['quality_claim_allowed']}`",
        "",
        "## Voice Design Profiles",
    ]
    for profile in payload["voice_design_profiles"]:
        lines.extend(
            [
                "",
                f"### {profile['profile_id']}",
                "",
                f"- Language: `{profile['language']}`",
                f"- Recommended voice name: `{profile['recommended_voice_name']}`",
                f"- Preview text: {profile['preview_text']}",
                f"- Prompt: {profile['voice_design_prompt']}",
            ]
        )

    lines.extend(["", "## Voice Design UI Candidates"])
    for candidate in payload["voice_design_ui_candidates"]:
        lines.extend(
            [
                "",
                f"### {candidate['candidate_id']}",
                "",
                f"- Use: {candidate['recommended_use']}",
                f"- Loudness: `{candidate['loudness']}`",
                f"- Guidance scale: `{candidate['guidance_scale']}`",
                f"- Expected effect: {candidate['expected_effect']}",
            ]
        )

    lines.extend(["", "## Voice Remixing Prompts"])
    for prompt in payload["voice_remixing_prompts"]:
        lines.extend(
            [
                "",
                f"### {prompt['remix_prompt_id']}",
                "",
                f"- Language: `{prompt['language']}`",
                f"- Recommended prompt strength: `{prompt['recommended_prompt_strength']}`",
                f"- Fallback strength: `{prompt['fallback_prompt_strength_if_too_subtle']}`",
                f"- Categories: `{', '.join(prompt['categories'])}`",
                f"- Prompt: {prompt['prompt']}",
                f"- Custom script: {prompt['custom_script']}",
                f"- Success criteria: `{'; '.join(prompt['success_criteria'])}`",
            ]
        )

    lines.extend(["", "## Settings Matrix"])
    for candidate in payload["settings_matrix"]:
        lines.extend(
            [
                "",
                f"### {candidate['candidate_id']}",
                "",
                f"- Use: {candidate['recommended_use']}",
                f"- Model family: `{candidate['model_family']}`",
                f"- Stability: `{candidate['stability']}`",
                f"- Similarity boost: `{candidate['similarity_boost']}`",
                f"- Style: `{candidate['style']}`",
                f"- Speed: `{candidate['speed']}`",
                f"- Speaker boost: `{candidate['use_speaker_boost']}`",
                f"- Latency risk: `{candidate['latency_risk']}`",
            ]
        )

    lines.extend(["", "## Emotional Delivery Bundles"])
    for bundle in payload["emotional_delivery_bundles"]:
        lines.extend(
            [
                "",
                f"### {bundle['bundle_id']}",
                "",
                f"- Trigger: {bundle['trigger']}",
                f"- Blocked in protected text: `{bundle['blocked_in_protected_text']}`",
                f"- Combined effects: `{'; '.join(bundle['combined_effects'])}`",
            ]
        )

    lines.extend(
        [
            "",
            "## Protected Text Boundary",
            "",
            f"- Exact text lock: `{payload['protected_text_rules']['exact_text_lock']}`",
            f"- Fillers allowed: `{payload['protected_text_rules']['filler_words_allowed']}`",
            f"- Random spacing allowed: `{payload['protected_text_rules']['random_spacing_allowed']}`",
            f"- Delivery: `{payload['protected_text_rules']['allowed_delivery']}`",
            "",
            "## Dashboard Steps",
            "",
        ]
    )
    for step in payload["dashboard_steps"]:
        lines.append(f"- {step}")
    lines.extend(
        [
            "",
            "## Product Meaning",
            "",
            "VOICE-020 turns the voice work from local text shaping into a provider-aware voice design packet. The next live step is to create or select English and German ElevenLabs voices from these prompts and compare the settings candidates on synthetic sales-agent samples.",
            "",
        ]
    )
    return "\n".join(lines)


def build_payload(cases_path: Path) -> dict[str, Any]:
    config = load_json(cases_path)
    available_sources = load_available_sources(config["source_artifacts"])
    return {
        "voice_milestone": VOICE_MILESTONE,
        "experiment_scope": config["experiment_scope"],
        "case_file": project_relative_string(cases_path),
        "source_artifacts": available_sources,
        "official_sources": config["official_sources"],
        "listening_feedback_basis": config["listening_feedback_basis"],
        "private_call_center_boundary": config["private_call_center_boundary"],
        "voice_design_ui_candidates": config["voice_design_ui_candidates"],
        "voice_remixing_prompts": config["voice_remixing_prompts"],
        "voice_design_profiles": config["voice_design_profiles"],
        "settings_matrix": config["settings_matrix"],
        "emotional_delivery_bundles": config["emotional_delivery_bundles"],
        "protected_text_rules": config["protected_text_rules"],
        "dashboard_steps": build_dashboard_steps(config),
        "summary": summarize(config, available_sources),
        "runtime_boundary": {
            "offline_design_only": True,
            "provider_calls_made": False,
            "requires_api_key": False,
            "customer_audio_uploaded": False,
            "private_audio_uploaded": False,
            "voice_cloning_used": False,
            "generated_audio_created": False,
            "quality_claim_allowed_without_human_rating": False,
            "provider_input_allowed_now": "synthetic voice-design prompts and synthetic preview text only",
        },
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the VOICE-020 ElevenLabs voice design packet.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES), help="VOICE-020 case/config file.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Path to write JSON output.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Path to write Markdown report.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    if cases_path is None or out_path is None or report_path is None:
        raise SystemExit("Cases, output, and report paths are required.")

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))
    print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
