#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from speech_realism import apply_speech_realism


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES_PATH = ROOT / "research" / "experiments" / "cases" / "voice-025-filler-placement.json"
DEFAULT_RUN_DIR = ROOT / "research" / "experiments" / "generated" / "VOICE-025-filler-placement"
DEFAULT_OUT_PATH = DEFAULT_RUN_DIR / "results.json"
DEFAULT_REPORT_PATH = DEFAULT_RUN_DIR / "report.md"


def resolve_project_path(value: str | None, default: Path) -> Path:
    if not value:
        return default
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    return path


def project_relative_string(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def find_campaign(campaigns: list[dict[str, Any]], campaign_id: str) -> dict[str, Any]:
    for campaign in campaigns:
        if campaign.get("campaign_id") == campaign_id:
            return campaign
    raise KeyError(f"Campaign not found: {campaign_id}")


def run_case(case: dict[str, Any], campaigns: list[dict[str, Any]]) -> dict[str, Any]:
    campaign = find_campaign(campaigns, case["campaign_id"])
    packet = apply_speech_realism(
        campaign=campaign,
        segments=case["segments"],
        language=case.get("language") or campaign.get("language"),
        seed=case["case_id"],
        customer_state=case.get("customer_state"),
    )
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": packet["language"],
        "speech_realism": packet,
    }


def aggregate(results: list[dict[str, Any]]) -> dict[str, Any]:
    language_counts: dict[str, int] = {}
    insertion_strategies: dict[str, int] = {}
    fillers: dict[str, int] = {}
    protected_segment_change_count = 0

    for result in results:
        packet = result["speech_realism"]
        language_counts[result["language"]] = language_counts.get(result["language"], 0) + 1
        protected_segment_change_count += len(packet["validation"]["protected_segment_changes"])
        for bundle in packet["speech_bundles"]:
            strategy = bundle.get("insertion_strategy", "unknown")
            insertion_strategies[strategy] = insertion_strategies.get(strategy, 0) + 1
            filler = bundle.get("filler", "none")
            fillers[filler] = fillers.get(filler, 0) + 1

    return {
        "case_count": len(results),
        "languages": language_counts,
        "bundle_count": sum(result["speech_realism"]["bundle_count"] for result in results),
        "insertion_strategies": insertion_strategies,
        "fillers": fillers,
        "validation_passed": sum(1 for result in results if result["speech_realism"]["validation"]["passed"]),
        "validation_failed": sum(1 for result in results if not result["speech_realism"]["validation"]["passed"]),
        "protected_segment_change_count": protected_segment_change_count,
        "provider_calls_made": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
    }


def build_payload(cases_path: Path) -> dict[str, Any]:
    cases_doc = load_json(cases_path)
    results = [run_case(case, cases_doc["campaigns"]) for case in cases_doc["cases"]]
    return {
        "voice_milestone": cases_doc.get("voice_milestone", "VOICE-025"),
        "experiment_scope": cases_doc.get("experiment_scope"),
        "case_source": project_relative_string(cases_path),
        "results": results,
        "summary": aggregate(results),
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-025 Filler Placement Report",
        "",
        "This report was generated by `scripts/run_voice_025_filler_placement.py`.",
        "",
        "VOICE-025 refines the VOICE-023 speech-realism layer by moving English and German fillers to planning, sentence, or discourse boundaries instead of inserting them inside fluent clause frames.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['languages'].get('de', 0)}`",
        f"- English cases: `{summary['languages'].get('en', 0)}`",
        f"- Bundle count: `{summary['bundle_count']}`",
        f"- Insertion strategies: `{summary['insertion_strategies']}`",
        f"- Fillers: `{summary['fillers']}`",
        f"- Protected segment changes: `{summary['protected_segment_change_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        "",
        "## Boundary Rule",
        "",
        "- Prefer pre-answer or pre-planning-sentence placement.",
        "- Prefer sentence-boundary fallback when no planning phrase is found.",
        "- Avoid mid-clause filler insertion such as `The important thing is, um, that...` or `Wichtig ist, ähm, dass...`.",
        "- Keep campaign questions, disclosures, compliance lines, hangup lines, and exact client script text unchanged.",
        "",
        "## Case Results",
    ]

    for result in payload["results"]:
        packet = result["speech_realism"]
        lines.extend(
            [
                "",
                f"### {result['case_id']}: {result['case_title']}",
                "",
                f"- Campaign: `{result['campaign_id']}`",
                f"- Language: `{result['language']}`",
                f"- Bundle count: `{packet['bundle_count']}`",
                f"- Validation passed: `{packet['validation']['passed']}`",
                f"- TTS text: {packet['tts_text']}",
            ]
        )
        for bundle in packet["speech_bundles"]:
            lines.append(
                f"- `{bundle['bundle_type']}` on `{bundle['segment_id']}`: filler `{bundle['filler']}`, strategy `{bundle.get('insertion_strategy')}`, position `{bundle.get('position')}`, pause `{bundle['pause_ms']}ms`, rate `{bundle['rate_after']}`"
            )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the VOICE-025 filler placement offline checkpoint.")
    parser.add_argument("--cases", help="Input VOICE-025 case JSON path.")
    parser.add_argument("--out", help="Output JSON path.")
    parser.add_argument("--report-out", help="Output Markdown report path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases, DEFAULT_CASES_PATH)
    out_path = resolve_project_path(args.out, DEFAULT_OUT_PATH)
    report_path = resolve_project_path(args.report_out, DEFAULT_REPORT_PATH)

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))

    print(f"Wrote VOICE-025 results to {project_relative_string(out_path)}")
    print(f"Wrote VOICE-025 report to {project_relative_string(report_path)}")


if __name__ == "__main__":
    main()
