#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from speech_imperfections import EVALUATION_RUBRIC, apply_speech_imperfections


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES_PATH = ROOT / "research" / "experiments" / "cases" / "voice-028-controlled-imperfections.json"
DEFAULT_RUN_DIR = ROOT / "research" / "experiments" / "generated" / "VOICE-028-controlled-imperfections"
DEFAULT_OUT_PATH = DEFAULT_RUN_DIR / "results.json"
DEFAULT_REPORT_PATH = DEFAULT_RUN_DIR / "report.md"


def resolve_project_path(value: str | None, default: Path) -> Path:
    if not value:
        return default
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    return path


def project_relative_string(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def find_campaign(campaigns: list[dict[str, Any]], campaign_id: str) -> dict[str, Any]:
    for campaign in campaigns:
        if campaign.get("campaign_id") == campaign_id:
            return campaign
    raise KeyError(f"Campaign not found: {campaign_id}")


def run_case(case: dict[str, Any], campaigns: list[dict[str, Any]]) -> dict[str, Any]:
    campaign = find_campaign(campaigns, case["campaign_id"])
    packet = apply_speech_imperfections(
        campaign=campaign,
        segments=case["segments"],
        language=case.get("language") or campaign.get("language"),
        seed=case["case_id"],
        customer_state=case.get("customer_state"),
    )
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": packet["language"],
        "speech_imperfections": packet,
    }


def aggregate(results: list[dict[str, Any]]) -> dict[str, Any]:
    language_counts: dict[str, int] = {}
    imperfection_types: dict[str, int] = {}
    protected_segment_change_count = 0
    unsafe_visible_imperfection_count = 0

    for result in results:
        packet = result["speech_imperfections"]
        language_counts[result["language"]] = language_counts.get(result["language"], 0) + 1
        protected_segment_change_count += len(packet["validation"]["protected_segment_changes"])
        unsafe_visible_imperfection_count += len(packet["validation"]["unsafe_visible_imperfections"])
        for imperfection in packet["imperfections"]:
            imperfection_type = imperfection.get("imperfection_type", "unknown")
            imperfection_types[imperfection_type] = imperfection_types.get(imperfection_type, 0) + 1

    return {
        "case_count": len(results),
        "languages": language_counts,
        "imperfection_count": sum(result["speech_imperfections"]["imperfection_count"] for result in results),
        "imperfection_types": imperfection_types,
        "validation_passed": sum(1 for result in results if result["speech_imperfections"]["validation"]["passed"]),
        "validation_failed": sum(1 for result in results if not result["speech_imperfections"]["validation"]["passed"]),
        "protected_segment_change_count": protected_segment_change_count,
        "unsafe_visible_imperfection_count": unsafe_visible_imperfection_count,
        "provider_calls_made": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
    }


def build_payload(cases_path: Path) -> dict[str, Any]:
    cases_doc = load_json(cases_path)
    results = [run_case(case, cases_doc["campaigns"]) for case in cases_doc["cases"]]
    return {
        "voice_milestone": cases_doc.get("voice_milestone", "VOICE-028"),
        "experiment_scope": cases_doc.get("experiment_scope"),
        "case_source": project_relative_string(cases_path),
        "evaluation_rubric": EVALUATION_RUBRIC,
        "results": results,
        "summary": aggregate(results),
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-028 Controlled Imperfections Report",
        "",
        "This report was generated by `scripts/run_voice_028_controlled_imperfections.py`.",
        "",
        "VOICE-028 adds professional, bounded speech imperfections to eligible freeform delivery so the agent does not sound like perfectly rendered text.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['languages'].get('de', 0)}`",
        f"- English cases: `{summary['languages'].get('en', 0)}`",
        f"- Imperfection count: `{summary['imperfection_count']}`",
        f"- Imperfection types: `{summary['imperfection_types']}`",
        f"- Protected segment changes: `{summary['protected_segment_change_count']}`",
        f"- Unsafe visible imperfections: `{summary['unsafe_visible_imperfection_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{summary['voice_cloning_used']}`",
        "",
        "## Controlled Imperfection Rule",
        "",
        "- Add at most one small imperfection per response by default.",
        "- Prefer sentence-boundary clarifying rephrases or soft restarts.",
        "- Keep the style professional; do not make the agent sound sloppy, confused, or evasive.",
        "- Suppress visible imperfections around unsafe claims, stop intent, anger, handoff, and protected text.",
        "- Keep campaign questions, disclosures, appointment details, human handoff scripts, hangup lines, and compliance statements exact.",
        "- Keep this checkpoint offline: no TTS provider call, no customer audio upload, and no voice cloning.",
        "",
        "## Listening Rubric",
        "",
    ]
    for key, value in payload["evaluation_rubric"].items():
        lines.append(f"- `{key}`: {value}")

    lines.append("")
    lines.append("## Case Results")

    for result in payload["results"]:
        packet = result["speech_imperfections"]
        lines.extend(
            [
                "",
                f"### {result['case_id']}: {result['case_title']}",
                "",
                f"- Campaign: `{result['campaign_id']}`",
                f"- Language: `{result['language']}`",
                f"- Imperfection count: `{packet['imperfection_count']}`",
                f"- Unsafe claim context: `{packet['unsafe_claim_context']}`",
                f"- Validation passed: `{packet['validation']['passed']}`",
                f"- TTS text: {packet['tts_text']}",
            ]
        )
        for imperfection in packet["imperfections"]:
            visible = "visible" if imperfection["visible"] else "non-visible"
            lines.append(
                f"- `{imperfection['imperfection_type']}` on `{imperfection['segment_id']}`: {visible}, placement `{imperfection['placement']}`, phrase `{imperfection['marker_text']}`, pause `{imperfection['pause_ms']}ms`"
            )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the VOICE-028 controlled imperfections offline checkpoint.")
    parser.add_argument("--cases", help="Input VOICE-028 case JSON path.")
    parser.add_argument("--out", help="Output JSON path.")
    parser.add_argument("--report-out", help="Output Markdown report path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases, DEFAULT_CASES_PATH)
    out_path = resolve_project_path(args.out, DEFAULT_OUT_PATH)
    report_path = resolve_project_path(args.report_out, DEFAULT_REPORT_PATH)

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))

    print(f"Wrote VOICE-028 results to {project_relative_string(out_path)}")
    print(f"Wrote VOICE-028 report to {project_relative_string(report_path)}")


if __name__ == "__main__":
    main()
