#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def load_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def render_prompt(template: str, case: dict) -> str:
    return template.format(
        dialogue_context=case["dialogue_context"],
        user_utterance=case["user_utterance"],
        emotion_label=case.get("emotion_label", ""),
        strategy_label=case.get("strategy_label", ""),
    )


def bullet_list(items):
    return "\n".join(f"- {item}" for item in items)


def build_case_section(case: dict, non_adaptive_prompt: str, adaptive_prompt: str) -> str:
    lines = [
        f"## {case['case_id']}",
        "",
        f"- Emotion label: `{case['emotion_label']}`",
        f"- Adaptive strategy label: `{case['strategy_label']}`",
    ]

    if case.get("source_grounding"):
        lines.extend(["", "Source grounding:", "", *[f"- {item}" for item in case["source_grounding"]]])

    if case.get("expected_adaptive_behavior"):
        lines.extend(["", "Expected adaptive behavior:", "", *[f"- {item}" for item in case["expected_adaptive_behavior"]]])

    lines.extend(
        [
            "",
            "Dialogue context:",
            "",
            "```text",
            case["dialogue_context"],
            "```",
            "",
            "Current user utterance:",
            "",
            "```text",
            case["user_utterance"],
            "```",
            "",
            "### Non-adaptive rendered prompt",
            "",
            "```text",
            non_adaptive_prompt.rstrip(),
            "```",
            "",
            "### Adaptive rendered prompt",
            "",
            "```text",
            adaptive_prompt.rstrip(),
            "```",
            "",
            "### Response slots",
            "",
            "Non-adaptive response:",
            "",
            "Adaptive response:",
            "",
            "### Rubric scores",
            "",
            "- Non-adaptive total:",
            "- Adaptive total:",
            "- Preferred:",
            "- Why:",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Render repeatable prompt-comparison packets from a structured case file.")
    parser.add_argument("--cases", required=True, help="Path to the JSON case file.")
    parser.add_argument("--out", required=True, help="Path to the markdown output file.")
    parser.add_argument(
        "--non-adaptive-prompt",
        default="packages/prompts/baseline-non-adaptive.txt",
        help="Path to the non-adaptive prompt template.",
    )
    parser.add_argument(
        "--adaptive-prompt",
        default="packages/prompts/baseline-adaptive.txt",
        help="Path to the adaptive prompt template.",
    )
    args = parser.parse_args()

    cases_path = Path(args.cases)
    out_path = Path(args.out)
    non_template = load_text(Path(args.non_adaptive_prompt))
    adaptive_template = load_text(Path(args.adaptive_prompt))
    cases = json.loads(load_text(cases_path))

    title = f"# Prompt Comparison Packet: {cases_path.stem}"
    header = [
        title,
        "",
        "This file was generated by `scripts/run_prompt_baseline.py`.",
        "",
        f"- Source case file: `{cases_path.as_posix()}`",
        f"- Cases: {len(cases)}",
        "",
        "Use this packet to run paired prompt comparisons in a repeatable way.",
        "",
    ]

    sections = []
    for case in cases:
        non_prompt = render_prompt(non_template, case)
        adaptive_prompt = render_prompt(adaptive_template, case)
        sections.append(build_case_section(case, non_prompt, adaptive_prompt))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(header + sections), encoding="utf-8")


if __name__ == "__main__":
    main()
