#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from rag_knowledge_base import build_source_manifest_template
from rag_notebooklm_automation import (
    DEFAULT_CHAT_CUSTOMIZATION_CHAR_LIMIT,
    DEFAULT_MIN_CHUNKS_PER_TOPIC,
    DEFAULT_PROMPT_CHAR_LIMIT,
    RAG_AUTOMATION_ID,
    build_notebooklm_prompt_pack,
    validate_extraction_output,
    validate_prompt_pack,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASE = ROOT / "research" / "experiments" / "cases" / "rag-002-notebooklm-extraction-automation-bridge.json"
DEFAULT_OUTPUT_DIR = ROOT / "research" / "experiments" / "generated" / "RAG-002-notebooklm-extraction-automation-bridge"
DEFAULT_RESULT = DEFAULT_OUTPUT_DIR / "result.json"
DEFAULT_REPORT = DEFAULT_OUTPUT_DIR / "report.md"
DEFAULT_PROMPT_DIR = DEFAULT_OUTPUT_DIR / "prompts"
DEFAULT_IMPORT_DIR = DEFAULT_OUTPUT_DIR / "imports"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip()).strip("-").lower()
    return slug or "topic"


def load_case(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def write_prompt_files(prompt_pack: dict[str, Any], prompt_dir: Path) -> list[dict[str, str]]:
    written: list[dict[str, str]] = []
    prompt_dir.mkdir(parents=True, exist_ok=True)
    chat_customization = prompt_pack.get("chat_customization") or {}
    chat_path = prompt_dir / "00-configure-chat-custom-instructions.md"
    chat_path.write_text(str(chat_customization.get("text", "")), encoding="utf-8")
    written.append(
        {
            "topic_id": "configure_chat",
            "prompt_type": "custom_instructions",
            "path": str(chat_path.relative_to(ROOT)).replace("\\", "/"),
            "char_count": str(chat_customization.get("char_count", 0)),
        }
    )
    for index, topic in enumerate(prompt_pack.get("topics", []), start=1):
        topic_slug = f"{index:02d}-{slugify(topic['topic_id'])}"
        topic_dir = prompt_dir / topic_slug
        topic_dir.mkdir(parents=True, exist_ok=True)
        prompt_file_names = {
            "report_artifact": "01-create-report-file.md",
            "primary_report": "02-chat-json-extraction.md",
            "gap_check": "03-gap-check.md",
        }
        for prompt_type in ("report_artifact", "primary_report", "gap_check"):
            prompt = topic["prompts"][prompt_type]
            filename = prompt_file_names[prompt_type]
            path = topic_dir / filename
            path.write_text(prompt["text"], encoding="utf-8")
            written.append(
                {
                    "topic_id": topic["topic_id"],
                    "prompt_type": prompt_type,
                    "path": str(path.relative_to(ROOT)).replace("\\", "/"),
                    "char_count": str(prompt["char_count"]),
                }
            )
    index_lines = [
        "# RAG-002 NotebookLM Prompt Index",
        "",
        "First paste `00-configure-chat-custom-instructions.md` into NotebookLM Configure Chat > Custom, and set response length to Longer.",
        "",
        "Then use each topic's `01-create-report-file.md` inside NotebookLM Reports / Create report. Use `02-chat-json-extraction.md` only if you need a stricter JSON handoff after the report exists.",
        "",
    ]
    for item in written:
        index_lines.append(f"- `{item['topic_id']}` `{item['prompt_type']}` `{item['char_count']} chars`: `{item['path']}`")
    (prompt_dir / "PROMPT_INDEX.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    return written


def write_import_readme(import_dir: Path) -> None:
    import_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# RAG-002 NotebookLM Import Drop Zone",
        "",
        "Paste or export NotebookLM JSON outputs here later, one file per topic.",
        "",
        "Rules:",
        "",
        "- keep raw source text, full transcripts, book chapters, private data, and API keys out of this folder",
        "- import only NotebookLM outputs that include `completion_status`, `coverage_checklist`, and `chunks`",
        "- outputs without `END: COMPLETE` are treated as partial and should be gap-checked before promotion",
        "- small sample batches should not be promoted into the local RAG base",
        "",
    ]
    (import_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def render_report(payload: dict[str, Any], prompt_files: list[dict[str, str]]) -> str:
    summary = payload["summary"]
    lines = [
        "# RAG-002 NotebookLM Extraction Automation Bridge Report",
        "",
        "This report was generated by `scripts/run_rag_002_notebooklm_extraction_automation.py`.",
        "",
        "RAG-002 automates the local side of NotebookLM extraction. It does not call NotebookLM, scrape the UI, or store raw source text.",
        "",
        "## Summary",
        "",
        f"- Topics: `{summary['topic_count']}`",
        f"- Prompts: `{summary['prompt_count']}`",
        f"- Prompt character limit: `{summary['prompt_char_limit']}`",
        f"- Configure Chat character limit: `{summary['chat_customization_char_limit']}`",
        f"- Configure Chat within limit: `{summary['chat_customization_within_limit']}`",
        f"- Report artifact workflow enabled: `{summary['report_artifact_workflow_enabled']}`",
        f"- Primary prompts include readable report: `{summary['primary_prompts_include_readable_report']}`",
        f"- Primary prompts include JSON block: `{summary['primary_prompts_include_json_block']}`",
        f"- All prompts within limit: `{summary['all_prompts_within_limit']}`",
        f"- Completion gate enabled: `{summary['completion_gate_enabled']}`",
        f"- Small sample batch rejection enabled: `{summary['small_batch_rejection_enabled']}`",
        f"- Manual NotebookLM UI required: `{summary['manual_notebooklm_ui_required']}`",
        f"- NotebookLM API used: `{summary['notebooklm_api_used']}`",
        f"- External provider calls made: `{summary['external_provider_calls_made']}`",
        f"- Raw source text stored: `{summary['raw_source_text_stored']}`",
        f"- Customer/private data used: `{summary['customer_private_data_used']}`",
        f"- Validation passed: `{summary['validation_passed']}`",
        "",
        "## How To Use",
        "",
        "1. Open NotebookLM Configure Chat.",
        "2. Select Custom and paste `00-configure-chat-custom-instructions.md`.",
        "3. Set response length to Longer and save.",
        "4. Open the matching NotebookLM notebook/topic.",
        "5. Use the topic's `report_artifact` prompt in NotebookLM Reports / Create report.",
        "6. Export or copy the completed report file after NotebookLM creates it.",
        "7. Use `primary_report` only if a stricter JSON handoff is needed after the report exists.",
        "8. If it returns a small sample batch, partial status, or `NEED_CONTINUATION`, paste the topic's `gap_check` prompt.",
        "9. Save the final exported report and/or JSON output into the generated `imports` folder for later validation/promotion.",
        "",
        "The prompt explicitly says: do not give a small sample batch. The local gate still rejects tiny or incomplete outputs, because NotebookLM may summarize unless we check it.",
        "",
        "## Prompt Files",
        "",
    ]
    for item in prompt_files:
        lines.append(f"- `{item['topic_id']}` `{item['prompt_type']}` `{item['char_count']} chars`: `{item['path']}`")
    lines.extend(
        [
            "",
            "## Import Gate",
            "",
            "A NotebookLM extraction is promotable only when it says `completion_status: complete`, confirms all selected sources were reviewed, sets `small_sample_batch: false`, includes `END: COMPLETE`, and meets the configured minimum chunk count unless the source material is explicitly insufficient.",
            "",
        ]
    )
    return "\n".join(lines)


def build_payload(
    case: dict[str, Any],
    *,
    prompt_char_limit: int,
    chat_customization_char_limit: int,
    min_chunks_per_topic: int,
) -> dict[str, Any]:
    manifest = case.get("source_manifest") or build_source_manifest_template()
    prompt_pack = build_notebooklm_prompt_pack(
        manifest,
        prompt_char_limit=prompt_char_limit,
        chat_customization_char_limit=chat_customization_char_limit,
        min_chunks_per_topic=min_chunks_per_topic,
    )
    prompt_validation = validate_prompt_pack(prompt_pack)
    extraction_reports = []
    for extraction_output in case.get("notebooklm_extraction_outputs", []):
        topic_id = extraction_output.get("topic_id", "")
        extraction_reports.append(
            validate_extraction_output(
                extraction_output,
                manifest,
                topic_id=topic_id,
                min_chunks_per_topic=min_chunks_per_topic,
            )
        )
    extraction_outputs_valid = all(report["passed"] for report in extraction_reports) if extraction_reports else True
    validation_passed = prompt_validation["passed"] and extraction_outputs_valid
    summary = {
        "topic_count": prompt_validation["topic_count"],
        "prompt_count": prompt_validation["prompt_count"],
        "prompt_char_limit": prompt_validation["prompt_char_limit"],
        "chat_customization_char_limit": prompt_validation["chat_customization_char_limit"],
        "chat_customization_within_limit": prompt_validation["chat_customization_within_limit"],
        "report_artifact_workflow_enabled": prompt_validation["report_artifact_workflow_enabled"],
        "primary_prompts_include_readable_report": prompt_validation["primary_prompts_include_readable_report"],
        "primary_prompts_include_json_block": prompt_validation["primary_prompts_include_json_block"],
        "all_prompts_within_limit": prompt_validation["all_prompts_within_limit"],
        "completion_gate_enabled": True,
        "small_batch_rejection_enabled": True,
        "manual_notebooklm_ui_required": prompt_validation["manual_notebooklm_ui_required"],
        "notebooklm_api_used": False,
        "external_provider_calls_made": False,
        "raw_source_text_stored": False,
        "customer_private_data_used": False,
        "validation_passed": validation_passed,
    }
    return {
        "rag_automation_id": RAG_AUTOMATION_ID,
        "title": case.get("title", "NotebookLM extraction automation bridge"),
        "description": case.get("description", ""),
        "summary": summary,
        "source_manifest": manifest,
        "prompt_pack": prompt_pack,
        "prompt_validation": prompt_validation,
        "extraction_validation": extraction_reports,
        "runtime_retrieval_enabled": False,
        "quality_claim_allowed": False,
        "private_data_boundary": {
            "customer_private_data_used": False,
            "raw_private_audio_used": False,
            "raw_private_transcripts_used": False,
            "provider_upload_used": False,
        },
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate RAG-002 NotebookLM extraction prompt packs and import gates.")
    parser.add_argument("--case", default=str(DEFAULT_CASE), help="RAG-002 case/input JSON.")
    parser.add_argument("--out", default=str(DEFAULT_RESULT), help="Output JSON path.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT), help="Output Markdown report path.")
    parser.add_argument("--prompt-dir", default=str(DEFAULT_PROMPT_DIR), help="Directory for generated per-topic prompts.")
    parser.add_argument("--import-dir", default=str(DEFAULT_IMPORT_DIR), help="Directory for future NotebookLM JSON imports.")
    parser.add_argument("--prompt-char-limit", type=int, default=DEFAULT_PROMPT_CHAR_LIMIT, help="Maximum characters per generated NotebookLM prompt.")
    parser.add_argument("--chat-customization-char-limit", type=int, default=DEFAULT_CHAT_CUSTOMIZATION_CHAR_LIMIT, help="Maximum characters for NotebookLM Configure Chat custom instructions.")
    parser.add_argument("--min-chunks-per-topic", type=int, default=DEFAULT_MIN_CHUNKS_PER_TOPIC, help="Minimum chunks expected per complete topic extraction unless source material is insufficient.")
    return parser.parse_args()


def resolve_path(path_value: str) -> Path:
    path = Path(path_value)
    return path if path.is_absolute() else ROOT / path


def main() -> None:
    args = parse_args()
    case_path = resolve_path(args.case)
    out_path = resolve_path(args.out)
    report_path = resolve_path(args.report_out)
    prompt_dir = resolve_path(args.prompt_dir)
    import_dir = resolve_path(args.import_dir)

    payload = build_payload(
        load_case(case_path),
        prompt_char_limit=args.prompt_char_limit,
        chat_customization_char_limit=args.chat_customization_char_limit,
        min_chunks_per_topic=args.min_chunks_per_topic,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    prompt_files = write_prompt_files(payload["prompt_pack"], prompt_dir)
    write_import_readme(import_dir)
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    report_path.write_text(render_report(payload, prompt_files), encoding="utf-8")
    print(json.dumps(payload["summary"], indent=2))
    raise SystemExit(0 if payload["summary"]["validation_passed"] else 1)


if __name__ == "__main__":
    main()
