#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from prosody_naturalness import apply_prosody_naturalness


ROOT = Path(__file__).resolve().parents[1]
VOICE_MILESTONE = "VOICE-015"
DEFAULT_CASES = ROOT / "research" / "experiments" / "cases" / "voice-015-prosody-naturalness.json"
DEFAULT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-015-prosody-naturalness.json"
DEFAULT_REPORT_OUT = ROOT / "research" / "experiments" / "generated" / "VOICE-015-prosody-naturalness-report.md"


def resolve_project_path(path_text: str | None) -> Path | None:
    if not path_text:
        return None
    path = Path(path_text)
    if path.is_absolute():
        return path
    return ROOT / path


def project_relative_string(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def find_campaign(campaigns: list[dict[str, Any]], campaign_id: str) -> dict[str, Any]:
    for campaign in campaigns:
        if campaign.get("campaign_id") == campaign_id:
            return campaign
    raise KeyError(f"Campaign not found: {campaign_id}")


def run_case(case: dict[str, Any], campaigns: list[dict[str, Any]]) -> dict[str, Any]:
    campaign = find_campaign(campaigns, case["campaign_id"])
    packet = apply_prosody_naturalness(
        campaign=campaign,
        segments=case["segments"],
        language=case.get("language") or campaign.get("language"),
        seed=case["case_id"],
    )
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": packet["language"],
        "expected": case.get("expected", {}),
        "prosody_naturalness": packet,
    }


def aggregate(results: list[dict[str, Any]]) -> dict[str, Any]:
    case_count = len(results)
    language_counts: dict[str, int] = {}
    aggregate_cues = {"emphasis": 0, "pause": 0, "pitch": 0, "rate": 0, "stretch": 0}
    profile_styles = set()

    for result in results:
        packet = result["prosody_naturalness"]
        language_counts[result["language"]] = language_counts.get(result["language"], 0) + 1
        profile_styles.add(packet["profile"]["style"])
        for cue_type, count in packet["cue_counts"].items():
            aggregate_cues[cue_type] = aggregate_cues.get(cue_type, 0) + count

    return {
        "case_count": case_count,
        "languages": language_counts,
        "profile_styles": sorted(profile_styles),
        "cue_count": sum(result["prosody_naturalness"]["cue_count"] for result in results),
        "cue_counts": aggregate_cues,
        "eligible_segment_count": sum(result["prosody_naturalness"]["eligible_segment_count"] for result in results),
        "protected_segment_count": sum(result["prosody_naturalness"]["protected_segment_count"] for result in results),
        "protected_segment_cue_count": sum(result["prosody_naturalness"]["protected_segment_cue_count"] for result in results),
        "validation_passed": sum(1 for result in results if result["prosody_naturalness"]["validation"]["passed"]),
        "validation_failed": sum(1 for result in results if not result["prosody_naturalness"]["validation"]["passed"]),
        "provider_calls_made": False,
        "requires_api_key": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-015 Prosody Naturalness Report",
        "",
        "This report was generated by `scripts/run_voice_015_prosody_naturalness.py`.",
        "",
        "VOICE-015 is provider-neutral and text-only. It creates bounded prosody cues for later TTS adapters, but makes no provider calls and uploads no customer audio.",
        "",
        "## Purpose",
        "",
        "Reduce robotic delivery by adding professional-human pause, rate, emphasis, pitch, and rare stretch cues while preserving protected campaign and compliance text exactly.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['languages'].get('de', 0)}`",
        f"- English cases: `{summary['languages'].get('en', 0)}`",
        f"- Profile styles: `{', '.join(summary['profile_styles'])}`",
        f"- Total cues: `{summary['cue_count']}`",
        f"- Pause cues: `{summary['cue_counts'].get('pause', 0)}`",
        f"- Pitch cues: `{summary['cue_counts'].get('pitch', 0)}`",
        f"- Rate cues: `{summary['cue_counts'].get('rate', 0)}`",
        f"- Emphasis cues: `{summary['cue_counts'].get('emphasis', 0)}`",
        f"- Stretch cues: `{summary['cue_counts'].get('stretch', 0)}`",
        f"- Protected-segment cues: `{summary['protected_segment_cue_count']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        "",
        "## Cue Boundary",
        "",
        "The clean `tts_text` stays plain. Human review can inspect `debug_text`, where emphasis may appear as Markdown bold and rare stretch cues may appear as ellipsis variants. Provider adapters must translate the structured `prosody_plan` safely rather than blindly sending debug markup.",
        "",
        "## Case Results",
    ]

    for result in payload["results"]:
        packet = result["prosody_naturalness"]
        validation = packet["validation"]
        lines.extend(
            [
                "",
                f"### {result['case_id']}: {result['case_title']}",
                "",
                f"- Campaign: `{result['campaign_id']}`",
                f"- Language: `{result['language']}`",
                f"- Cue count: `{packet['cue_count']}`",
                f"- Cue counts: `{packet['cue_counts']}`",
                f"- Eligible segments: `{packet['eligible_segment_count']}`",
                f"- Protected segments: `{packet['protected_segment_count']}`",
                f"- Validation passed: `{validation['passed']}`",
                f"- Clean TTS text: {packet['tts_text']}",
                f"- Debug text: {packet['debug_text']}",
            ]
        )
        for cue in packet["prosody_plan"]:
            target = cue.get("target") or cue.get("after")
            detail = cue.get("direction") or cue.get("mode") or cue.get("strength") or cue.get("variant")
            lines.append(
                f"- Cue `{cue['cue_id']}` `{cue['type']}` on segment `{cue['segment_id']}`: `{target}` / `{detail}`"
            )
    return "\n".join(lines) + "\n"


def build_payload(cases_path: Path) -> dict[str, Any]:
    case_file = load_json(cases_path)
    campaigns = case_file["campaigns"]
    results = [run_case(case, campaigns) for case in case_file["cases"]]
    return {
        "voice_milestone": VOICE_MILESTONE,
        "experiment_scope": case_file.get("experiment_scope"),
        "case_file": project_relative_string(cases_path),
        "summary": aggregate(results),
        "runtime_boundary": {
            "text_only": True,
            "provider_calls_made": False,
            "requires_api_key": False,
            "customer_audio_uploaded": False,
            "voice_cloning_used": False,
            "safe_default": "local deterministic prosody planning only",
        },
        "results": results,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run VOICE-015 segment-aware prosody naturalness cases.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES), help="VOICE-015 case file.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="JSON output path.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT_OUT), help="Markdown report output path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases)
    out_path = resolve_project_path(args.out)
    report_path = resolve_project_path(args.report_out)
    if cases_path is None or out_path is None or report_path is None:
        raise SystemExit("Cases, output, and report paths are required.")

    payload = build_payload(cases_path)
    write_json(out_path, payload)
    write_text(report_path, render_report(payload))
    print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
