#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from generate_guarded_response import build_guarded_response_packet
from realtime_turn_cli import find_campaign
from run_realtime_turn_simulation import load_realtime_cases
from runtime_voice_delivery import attach_runtime_voice_delivery


ROOT = Path(__file__).resolve().parents[1]
VOICE_MILESTONE = "VOICE-035"
DEFAULT_CASES = ROOT / "research" / "experiments" / "cases" / "voice-035-connected-speech-phrase-flow.json"
DEFAULT_OUT_DIR = ROOT / "research" / "experiments" / "generated" / "VOICE-035-connected-speech"


def resolve_project_path(path_text: str | None, default: Path | None = None) -> Path:
    if path_text:
        path = Path(path_text)
        return path if path.is_absolute() else ROOT / path
    if default is None:
        raise SystemExit("Missing required path.")
    return default


def project_relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build_case_result(case: dict[str, Any], campaign: dict[str, Any], provider: str) -> dict[str, Any]:
    guarded_packet = build_guarded_response_packet(
        campaign=campaign,
        stage=case["stage"],
        input_type="speech-final",
        transcript=case["transcript"],
        silence_count=int(case.get("silence_count", 0)),
        candidate_response_override=case.get("candidate_response"),
    )
    packet = attach_runtime_voice_delivery(guarded_packet, campaign, provider_key=provider)
    delivery = packet["voice_delivery"]
    connected = delivery["voice_connected_speech"]
    provider_rendering = connected["connected_provider_rendering"]
    return {
        "case_id": case["case_id"],
        "case_title": case["case_title"],
        "campaign_id": case["campaign_id"],
        "language": delivery["language"],
        "expected_connected_speech": case["expected_connected_speech"],
        "segment_type": delivery["segments"][0]["segment_type"],
        "final_response_unchanged": delivery["final_response_unchanged"],
        "connected_speech": connected,
        "provider_rendering": {
            "provider_key": provider_rendering["provider_key"],
            "rendered_text": provider_rendering["rendered_text"],
            "voice_settings": provider_rendering.get("voice_settings") or {},
            "pacing_calibrated": provider_rendering.get("pacing_calibrated", False),
            "connected_speech_applied": provider_rendering.get("connected_speech_applied", False),
            "provider_tag_count": provider_rendering.get("provider_tag_count", 0),
        },
        "validation": {
            "passed": connected["validation"]["passed"] and delivery["validation"]["passed"],
            "runtime_voice_validation_passed": delivery["validation"]["passed"],
            "connected_speech_validation_passed": connected["validation"]["passed"],
        },
    }


def aggregate(cases: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "case_count": len(cases),
        "german_cases": sum(1 for case in cases if case["language"] == "de"),
        "english_cases": sum(1 for case in cases if case["language"] == "en"),
        "flow_join_cases": sum(1 for case in cases if case["connected_speech"]["flow_join_count"] > 0),
        "protected_case_count": sum(1 for case in cases if case["connected_speech"]["flow_join_count"] == 0),
        "total_flow_joins": sum(int(case["connected_speech"]["flow_join_count"]) for case in cases),
        "validation_passed": sum(1 for case in cases if case["validation"]["passed"]),
        "provider_calls_made": False,
        "requires_api_key": False,
        "customer_audio_uploaded": False,
        "voice_cloning_used": False,
        "generated_audio_created": False,
        "quality_claim_allowed": False,
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# VOICE-035 Connected Speech Phrase Flow Report",
        "",
        "This report was generated by `scripts/run_voice_035_connected_speech.py`.",
        "",
        "VOICE-035 is offline and no-key. It joins obvious eligible freeform filler/bridge boundaries in provider-facing TTS text only, after VOICE-034 pacing calibration.",
        "",
        "## Summary",
        "",
        f"- Cases: `{summary['case_count']}`",
        f"- German cases: `{summary['german_cases']}`",
        f"- English cases: `{summary['english_cases']}`",
        f"- Flow-join cases: `{summary['flow_join_cases']}`",
        f"- Protected cases: `{summary['protected_case_count']}`",
        f"- Total flow joins: `{summary['total_flow_joins']}`",
        f"- Validation passed: `{summary['validation_passed']} / {summary['case_count']}`",
        f"- Provider calls made: `{summary['provider_calls_made']}`",
        f"- Customer audio uploaded: `{summary['customer_audio_uploaded']}`",
        f"- Voice cloning used: `{summary['voice_cloning_used']}`",
        "",
        "## Case Results",
        "",
    ]
    for case in payload["cases"]:
        connected = case["connected_speech"]
        lines.extend(
            [
                f"### {case['case_id']}: {case['case_title']}",
                "",
                f"- Language: `{case['language']}`",
                f"- Segment type: `{case['segment_type']}`",
                f"- Expected connected speech: `{case['expected_connected_speech']}`",
                f"- Flow joins: `{connected['flow_join_count']}`",
                f"- Tuned segments: `{connected['tuned_segment_count']}`",
                f"- Provider tags after flow join: `{case['provider_rendering']['provider_tag_count']}`",
                f"- Voice speed: `{case['provider_rendering']['voice_settings'].get('speed', 1.0)}`",
                f"- Validation passed: `{case['validation']['passed']}`",
                f"- Rendered text: {case['provider_rendering']['rendered_text']}",
                "",
            ]
        )
    lines.extend(
        [
            "## Boundary",
            "",
            "- No provider calls.",
            "- No generated audio.",
            "- No customer/private audio.",
            "- No voice cloning.",
            "- No final-response rewrite.",
            "- Protected campaign, compliance, handoff, hangup, and do-not-call text stays exact.",
        ]
    )
    return "\n".join(lines) + "\n"


def build_payload(cases_path: Path) -> dict[str, Any]:
    config = load_json(cases_path)
    source_cases_path = resolve_project_path(config["source_cases"])
    campaigns, _runtime_cases = load_realtime_cases(source_cases_path)
    provider = config.get("provider", "elevenlabs")
    cases = [
        build_case_result(case, find_campaign(campaigns, case["campaign_id"]), provider)
        for case in config["runtime_cases"]
    ]
    return {
        "voice_milestone": VOICE_MILESTONE,
        "experiment_scope": config["experiment_scope"],
        "case_file": project_relative(cases_path),
        "source_cases": project_relative(source_cases_path),
        "connected_speech_policy": config["connected_speech_policy"],
        "summary": aggregate(cases),
        "runtime_boundary": {
            "offline_preview_only": True,
            "provider_calls_made": False,
            "requires_api_key": False,
            "customer_audio_uploaded": False,
            "voice_cloning_used": False,
            "generated_audio_created": False,
            "quality_claim_allowed_without_human_rating": False,
        },
        "cases": cases,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run VOICE-035 offline connected-speech phrase-flow tuning.")
    parser.add_argument("--cases", default=str(DEFAULT_CASES), help="VOICE-035 case/config file.")
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR), help="Output directory for results.json and report.md.")
    parser.add_argument("--print-json", action="store_true", help="Print the full payload after writing artifacts.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases_path = resolve_project_path(args.cases, DEFAULT_CASES)
    out_dir = resolve_project_path(args.out_dir, DEFAULT_OUT_DIR)
    payload = build_payload(cases_path)
    write_json(out_dir / "results.json", payload)
    write_text(out_dir / "report.md", render_report(payload))
    if args.print_json:
        print(json.dumps(payload, indent=2, ensure_ascii=False))
    else:
        print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
