#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from rag_knowledge_base import (
    RAG_INTAKE_ID,
    build_knowledge_base,
    build_notebooklm_extraction_prompt,
    build_source_manifest_template,
    get_topic_taxonomy,
    validate_notebooklm_chunks,
    validate_source_manifest,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASE = ROOT / "research" / "experiments" / "cases" / "rag-001-notebooklm-source-intake-bridge.json"
DEFAULT_OUTPUT_DIR = ROOT / "research" / "experiments" / "generated" / "RAG-001-notebooklm-source-intake-bridge"
DEFAULT_RESULT = DEFAULT_OUTPUT_DIR / "result.json"
DEFAULT_REPORT = DEFAULT_OUTPUT_DIR / "report.md"


def load_case(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# RAG-001 NotebookLM Source Intake Bridge Report",
        "",
        "This report was generated by `scripts/run_rag_001_notebooklm_source_intake.py`.",
        "",
        "NotebookLM is used as an extraction helper, not permanent memory.",
        "",
        "## Summary",
        "",
        f"- Topics: `{summary['topic_count']}`",
        f"- Source slots: `{summary['source_count']}`",
        f"- Demo chunks: `{summary['chunk_count']}`",
        f"- All topics have source slots: `{summary['all_topics_have_source_slots']}`",
        f"- All chunks source-tracked: `{summary['all_chunks_source_tracked']}`",
        f"- NotebookLM API used: `{summary['notebooklm_api_used']}`",
        f"- External provider calls made: `{summary['external_provider_calls_made']}`",
        f"- Raw source text stored: `{summary['raw_source_text_stored']}`",
        f"- Customer/private data used: `{summary['customer_private_data_used']}`",
        f"- Validation passed: `{summary['validation_passed']}`",
        "",
        "## Topics",
        "",
    ]
    for topic in payload["topics"]:
        lines.append(f"- `{topic['topic_id']}`: {topic['label']}")
    lines.extend(["", "## Chunk Preview", ""])
    for chunk in payload["knowledge_base"]["chunks"]:
        source_ids = ", ".join(chunk.get("source_ids", []))
        topic_ids = ", ".join(chunk.get("topic_ids", []))
        lines.extend(
            [
                f"### {chunk['chunk_id']}",
                "",
                f"- Topics: `{topic_ids}`",
                f"- Sources: `{source_ids}`",
                f"- Principle: {chunk['principle']}",
                f"- Compliance notes: {chunk['compliance_notes']}",
                "",
            ]
        )
    lines.extend(
        [
            "## Next Human Step",
            "",
            "Replace the source slots with real source metadata, add the sources to NotebookLM, run the extraction prompt, then import the returned JSON chunks through this validator.",
            "",
            "Do not paste long copied passages, transcripts, chapters, API keys, private customer data, or private call-center material into tracked RAG chunks.",
            "",
        ]
    )
    return "\n".join(lines)


def build_payload(case: dict[str, Any]) -> dict[str, Any]:
    manifest = case.get("source_manifest") or build_source_manifest_template()
    if "topics" not in manifest:
        manifest["topics"] = get_topic_taxonomy()
    chunks = case.get("notebooklm_extracted_chunks") or []
    manifest_validation = validate_source_manifest(manifest)
    chunk_validation = validate_notebooklm_chunks(chunks, manifest)
    knowledge_base = build_knowledge_base(chunks, manifest)
    prompt = build_notebooklm_extraction_prompt(manifest)
    validation_passed = manifest_validation["passed"] and chunk_validation["passed"] and knowledge_base["source_traceability"]["all_chunks_source_tracked"]
    summary = {
        "topic_count": len(get_topic_taxonomy()),
        "source_count": len(manifest.get("sources", [])),
        "chunk_count": len(chunks),
        "all_topics_have_source_slots": manifest_validation["all_topic_slots_present"],
        "all_chunks_source_tracked": knowledge_base["source_traceability"]["all_chunks_source_tracked"],
        "notebooklm_api_used": False,
        "external_provider_calls_made": False,
        "raw_source_text_stored": manifest_validation["raw_source_text_stored"] or chunk_validation["raw_source_text_stored"],
        "customer_private_data_used": False,
        "validation_passed": validation_passed,
    }
    return {
        "rag_intake_id": RAG_INTAKE_ID,
        "title": case.get("title", "NotebookLM source intake bridge"),
        "description": case.get("description", ""),
        "summary": summary,
        "topics": get_topic_taxonomy(),
        "source_manifest": manifest,
        "manifest_validation": manifest_validation,
        "notebooklm_extraction_prompt": prompt,
        "chunk_validation": chunk_validation,
        "knowledge_base": knowledge_base,
        "quality_claim_allowed": False,
        "runtime_retrieval_enabled": False,
        "private_data_boundary": {
            "customer_private_data_used": False,
            "raw_private_audio_used": False,
            "raw_private_transcripts_used": False,
            "provider_upload_used": False,
        },
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create RAG-001 NotebookLM source-intake bridge artifacts.")
    parser.add_argument("--case", default=str(DEFAULT_CASE), help="RAG-001 case/input JSON.")
    parser.add_argument("--out", default=str(DEFAULT_RESULT), help="Output JSON path.")
    parser.add_argument("--report-out", default=str(DEFAULT_REPORT), help="Output Markdown report path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    case_path = Path(args.case)
    if not case_path.is_absolute():
        case_path = ROOT / case_path
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = ROOT / out_path
    report_path = Path(args.report_out)
    if not report_path.is_absolute():
        report_path = ROOT / report_path

    payload = build_payload(load_case(case_path))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    report_path.write_text(render_report(payload), encoding="utf-8")
    print(json.dumps(payload["summary"], indent=2))
    raise SystemExit(0 if payload["summary"]["validation_passed"] else 1)


if __name__ == "__main__":
    main()
